// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.openim.android.sdk.protos.user;

public interface GetDesignateUsersRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.user.GetDesignateUsersResp)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .openim.sdkws.UserInfo usersInfo = 1;</code>
   */
  java.util.List<io.openim.android.sdk.protos.sdkws.UserInfo> 
      getUsersInfoList();
  /**
   * <code>repeated .openim.sdkws.UserInfo usersInfo = 1;</code>
   */
  io.openim.android.sdk.protos.sdkws.UserInfo getUsersInfo(int index);
  /**
   * <code>repeated .openim.sdkws.UserInfo usersInfo = 1;</code>
   */
  int getUsersInfoCount();
}
