// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.openim.android.sdk.protos.user;

public interface OnlineStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.user.OnlineStatus)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @return A list containing the platformIDs.
   */
  java.util.List<java.lang.Integer> getPlatformIDsList();
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @return The count of platformIDs.
   */
  int getPlatformIDsCount();
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @param index The index of the element to return.
   * @return The platformIDs at the given index.
   */
  int getPlatformIDs(int index);
}
