// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.openim.android.sdk.protos.user;

/**
 * Protobuf type {@code openim.user.OnlineStatus}
 */
public final class OnlineStatus extends
    com.google.protobuf.GeneratedMessageLite<
        OnlineStatus, OnlineStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.user.OnlineStatus)
    OnlineStatusOrBuilder {
  private OnlineStatus() {
    userID_ = "";
    platformIDs_ = emptyIntList();
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.String userID_;
  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  @java.lang.Override
  public java.lang.String getUserID() {
    return userID_;
  }
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userID_);
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The userID to set.
   */
  private void setUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userID_ = value;
  }
  /**
   * <code>string userID = 1;</code>
   */
  private void clearUserID() {
    
    userID_ = getDefaultInstance().getUserID();
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The bytes for userID to set.
   */
  private void setUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userID_ = value.toStringUtf8();
    
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }
  /**
   * <code>int32 status = 2;</code>
   * @param value The status to set.
   */
  private void setStatus(int value) {
    
    status_ = value;
  }
  /**
   * <code>int32 status = 2;</code>
   */
  private void clearStatus() {
    
    status_ = 0;
  }

  public static final int PLATFORMIDS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList platformIDs_;
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @return A list containing the platformIDs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getPlatformIDsList() {
    return platformIDs_;
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @return The count of platformIDs.
   */
  @java.lang.Override
  public int getPlatformIDsCount() {
    return platformIDs_.size();
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @param index The index of the element to return.
   * @return The platformIDs at the given index.
   */
  @java.lang.Override
  public int getPlatformIDs(int index) {
    return platformIDs_.getInt(index);
  }
  private int platformIDsMemoizedSerializedSize = -1;
  private void ensurePlatformIDsIsMutable() {
    com.google.protobuf.Internal.IntList tmp = platformIDs_;
    if (!tmp.isModifiable()) {
      platformIDs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @param index The index to set the value at.
   * @param value The platformIDs to set.
   */
  private void setPlatformIDs(
      int index, int value) {
    ensurePlatformIDsIsMutable();
    platformIDs_.setInt(index, value);
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @param value The platformIDs to add.
   */
  private void addPlatformIDs(int value) {
    ensurePlatformIDsIsMutable();
    platformIDs_.addInt(value);
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   * @param values The platformIDs to add.
   */
  private void addAllPlatformIDs(
      java.lang.Iterable<? extends java.lang.Integer> values) {
    ensurePlatformIDsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, platformIDs_);
  }
  /**
   * <code>repeated int32 platformIDs = 3;</code>
   */
  private void clearPlatformIDs() {
    platformIDs_ = emptyIntList();
  }

  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.user.OnlineStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.user.OnlineStatus prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.user.OnlineStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.user.OnlineStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.user.OnlineStatus)
      io.openim.android.sdk.protos.user.OnlineStatusOrBuilder {
    // Construct using io.openim.android.sdk.protos.user.OnlineStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string userID = 1;</code>
     * @return The userID.
     */
    @java.lang.Override
    public java.lang.String getUserID() {
      return instance.getUserID();
    }
    /**
     * <code>string userID = 1;</code>
     * @return The bytes for userID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      return instance.getUserIDBytes();
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserID(value);
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      copyOnWrite();
      instance.clearUserID();
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The bytes for userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIDBytes(value);
      return this;
    }

    /**
     * <code>int32 status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>int32 status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>int32 status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @return A list containing the platformIDs.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPlatformIDsList() {
      return java.util.Collections.unmodifiableList(
          instance.getPlatformIDsList());
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @return The count of platformIDs.
     */
    @java.lang.Override
    public int getPlatformIDsCount() {
      return instance.getPlatformIDsCount();
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @param index The index of the element to return.
     * @return The platformIDs at the given index.
     */
    @java.lang.Override
    public int getPlatformIDs(int index) {
      return instance.getPlatformIDs(index);
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @param value The platformIDs to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformIDs(
        int index, int value) {
      copyOnWrite();
      instance.setPlatformIDs(index, value);
      return this;
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @param value The platformIDs to add.
     * @return This builder for chaining.
     */
    public Builder addPlatformIDs(int value) {
      copyOnWrite();
      instance.addPlatformIDs(value);
      return this;
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @param values The platformIDs to add.
     * @return This builder for chaining.
     */
    public Builder addAllPlatformIDs(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllPlatformIDs(values);
      return this;
    }
    /**
     * <code>repeated int32 platformIDs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformIDs() {
      copyOnWrite();
      instance.clearPlatformIDs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.user.OnlineStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.user.OnlineStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userID_",
            "status_",
            "platformIDs_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\'";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.user.OnlineStatus> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.user.OnlineStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.user.OnlineStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.user.OnlineStatus)
  private static final io.openim.android.sdk.protos.user.OnlineStatus DEFAULT_INSTANCE;
  static {
    OnlineStatus defaultInstance = new OnlineStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OnlineStatus.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.user.OnlineStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OnlineStatus> PARSER;

  public static com.google.protobuf.Parser<OnlineStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

