// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/conversation.proto

package io.openim.android.sdk.protos.conversation;

/**
 * Protobuf type {@code openim.conversation.Conversation}
 */
public  final class Conversation extends
    com.google.protobuf.GeneratedMessageLite<
        Conversation, Conversation.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.conversation.Conversation)
    ConversationOrBuilder {
  private Conversation() {
    ownerUserID_ = "";
    conversationID_ = "";
    userID_ = "";
    groupID_ = "";
    attachedInfo_ = "";
    ex_ = "";
  }
  public static final int OWNERUSERID_FIELD_NUMBER = 1;
  private java.lang.String ownerUserID_;
  /**
   * <code>string ownerUserID = 1;</code>
   * @return The ownerUserID.
   */
  @java.lang.Override
  public java.lang.String getOwnerUserID() {
    return ownerUserID_;
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @return The bytes for ownerUserID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ownerUserID_);
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @param value The ownerUserID to set.
   */
  private void setOwnerUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ownerUserID_ = value;
  }
  /**
   * <code>string ownerUserID = 1;</code>
   */
  private void clearOwnerUserID() {
    
    ownerUserID_ = getDefaultInstance().getOwnerUserID();
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @param value The bytes for ownerUserID to set.
   */
  private void setOwnerUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ownerUserID_ = value.toStringUtf8();
    
  }

  public static final int CONVERSATIONID_FIELD_NUMBER = 2;
  private java.lang.String conversationID_;
  /**
   * <code>string conversationID = 2;</code>
   * @return The conversationID.
   */
  @java.lang.Override
  public java.lang.String getConversationID() {
    return conversationID_;
  }
  /**
   * <code>string conversationID = 2;</code>
   * @return The bytes for conversationID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conversationID_);
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The conversationID to set.
   */
  private void setConversationID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    conversationID_ = value;
  }
  /**
   * <code>string conversationID = 2;</code>
   */
  private void clearConversationID() {
    
    conversationID_ = getDefaultInstance().getConversationID();
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The bytes for conversationID to set.
   */
  private void setConversationIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conversationID_ = value.toStringUtf8();
    
  }

  public static final int RECVMSGOPT_FIELD_NUMBER = 3;
  private int recvMsgOpt_;
  /**
   * <code>int32 recvMsgOpt = 3;</code>
   * @return The recvMsgOpt.
   */
  @java.lang.Override
  public int getRecvMsgOpt() {
    return recvMsgOpt_;
  }
  /**
   * <code>int32 recvMsgOpt = 3;</code>
   * @param value The recvMsgOpt to set.
   */
  private void setRecvMsgOpt(int value) {
    
    recvMsgOpt_ = value;
  }
  /**
   * <code>int32 recvMsgOpt = 3;</code>
   */
  private void clearRecvMsgOpt() {
    
    recvMsgOpt_ = 0;
  }

  public static final int CONVERSATIONTYPE_FIELD_NUMBER = 4;
  private int conversationType_;
  /**
   * <code>int32 conversationType = 4;</code>
   * @return The conversationType.
   */
  @java.lang.Override
  public int getConversationType() {
    return conversationType_;
  }
  /**
   * <code>int32 conversationType = 4;</code>
   * @param value The conversationType to set.
   */
  private void setConversationType(int value) {
    
    conversationType_ = value;
  }
  /**
   * <code>int32 conversationType = 4;</code>
   */
  private void clearConversationType() {
    
    conversationType_ = 0;
  }

  public static final int USERID_FIELD_NUMBER = 5;
  private java.lang.String userID_;
  /**
   * <code>string userID = 5;</code>
   * @return The userID.
   */
  @java.lang.Override
  public java.lang.String getUserID() {
    return userID_;
  }
  /**
   * <code>string userID = 5;</code>
   * @return The bytes for userID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userID_);
  }
  /**
   * <code>string userID = 5;</code>
   * @param value The userID to set.
   */
  private void setUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userID_ = value;
  }
  /**
   * <code>string userID = 5;</code>
   */
  private void clearUserID() {
    
    userID_ = getDefaultInstance().getUserID();
  }
  /**
   * <code>string userID = 5;</code>
   * @param value The bytes for userID to set.
   */
  private void setUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userID_ = value.toStringUtf8();
    
  }

  public static final int GROUPID_FIELD_NUMBER = 6;
  private java.lang.String groupID_;
  /**
   * <code>string groupID = 6;</code>
   * @return The groupID.
   */
  @java.lang.Override
  public java.lang.String getGroupID() {
    return groupID_;
  }
  /**
   * <code>string groupID = 6;</code>
   * @return The bytes for groupID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(groupID_);
  }
  /**
   * <code>string groupID = 6;</code>
   * @param value The groupID to set.
   */
  private void setGroupID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    groupID_ = value;
  }
  /**
   * <code>string groupID = 6;</code>
   */
  private void clearGroupID() {
    
    groupID_ = getDefaultInstance().getGroupID();
  }
  /**
   * <code>string groupID = 6;</code>
   * @param value The bytes for groupID to set.
   */
  private void setGroupIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    groupID_ = value.toStringUtf8();
    
  }

  public static final int ISPINNED_FIELD_NUMBER = 7;
  private boolean isPinned_;
  /**
   * <code>bool isPinned = 7;</code>
   * @return The isPinned.
   */
  @java.lang.Override
  public boolean getIsPinned() {
    return isPinned_;
  }
  /**
   * <code>bool isPinned = 7;</code>
   * @param value The isPinned to set.
   */
  private void setIsPinned(boolean value) {
    
    isPinned_ = value;
  }
  /**
   * <code>bool isPinned = 7;</code>
   */
  private void clearIsPinned() {
    
    isPinned_ = false;
  }

  public static final int ATTACHEDINFO_FIELD_NUMBER = 8;
  private java.lang.String attachedInfo_;
  /**
   * <code>string attachedInfo = 8;</code>
   * @return The attachedInfo.
   */
  @java.lang.Override
  public java.lang.String getAttachedInfo() {
    return attachedInfo_;
  }
  /**
   * <code>string attachedInfo = 8;</code>
   * @return The bytes for attachedInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAttachedInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(attachedInfo_);
  }
  /**
   * <code>string attachedInfo = 8;</code>
   * @param value The attachedInfo to set.
   */
  private void setAttachedInfo(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    attachedInfo_ = value;
  }
  /**
   * <code>string attachedInfo = 8;</code>
   */
  private void clearAttachedInfo() {
    
    attachedInfo_ = getDefaultInstance().getAttachedInfo();
  }
  /**
   * <code>string attachedInfo = 8;</code>
   * @param value The bytes for attachedInfo to set.
   */
  private void setAttachedInfoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    attachedInfo_ = value.toStringUtf8();
    
  }

  public static final int ISPRIVATECHAT_FIELD_NUMBER = 9;
  private boolean isPrivateChat_;
  /**
   * <code>bool isPrivateChat = 9;</code>
   * @return The isPrivateChat.
   */
  @java.lang.Override
  public boolean getIsPrivateChat() {
    return isPrivateChat_;
  }
  /**
   * <code>bool isPrivateChat = 9;</code>
   * @param value The isPrivateChat to set.
   */
  private void setIsPrivateChat(boolean value) {
    
    isPrivateChat_ = value;
  }
  /**
   * <code>bool isPrivateChat = 9;</code>
   */
  private void clearIsPrivateChat() {
    
    isPrivateChat_ = false;
  }

  public static final int GROUPATTYPE_FIELD_NUMBER = 10;
  private int groupAtType_;
  /**
   * <code>int32 groupAtType = 10;</code>
   * @return The groupAtType.
   */
  @java.lang.Override
  public int getGroupAtType() {
    return groupAtType_;
  }
  /**
   * <code>int32 groupAtType = 10;</code>
   * @param value The groupAtType to set.
   */
  private void setGroupAtType(int value) {
    
    groupAtType_ = value;
  }
  /**
   * <code>int32 groupAtType = 10;</code>
   */
  private void clearGroupAtType() {
    
    groupAtType_ = 0;
  }

  public static final int EX_FIELD_NUMBER = 11;
  private java.lang.String ex_;
  /**
   * <code>string ex = 11;</code>
   * @return The ex.
   */
  @java.lang.Override
  public java.lang.String getEx() {
    return ex_;
  }
  /**
   * <code>string ex = 11;</code>
   * @return The bytes for ex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ex_);
  }
  /**
   * <code>string ex = 11;</code>
   * @param value The ex to set.
   */
  private void setEx(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ex_ = value;
  }
  /**
   * <code>string ex = 11;</code>
   */
  private void clearEx() {
    
    ex_ = getDefaultInstance().getEx();
  }
  /**
   * <code>string ex = 11;</code>
   * @param value The bytes for ex to set.
   */
  private void setExBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ex_ = value.toStringUtf8();
    
  }

  public static final int BURNDURATION_FIELD_NUMBER = 12;
  private int burnDuration_;
  /**
   * <code>int32 burnDuration = 12;</code>
   * @return The burnDuration.
   */
  @java.lang.Override
  public int getBurnDuration() {
    return burnDuration_;
  }
  /**
   * <code>int32 burnDuration = 12;</code>
   * @param value The burnDuration to set.
   */
  private void setBurnDuration(int value) {
    
    burnDuration_ = value;
  }
  /**
   * <code>int32 burnDuration = 12;</code>
   */
  private void clearBurnDuration() {
    
    burnDuration_ = 0;
  }

  public static final int MINSEQ_FIELD_NUMBER = 13;
  private long minSeq_;
  /**
   * <code>int64 minSeq = 13;</code>
   * @return The minSeq.
   */
  @java.lang.Override
  public long getMinSeq() {
    return minSeq_;
  }
  /**
   * <code>int64 minSeq = 13;</code>
   * @param value The minSeq to set.
   */
  private void setMinSeq(long value) {
    
    minSeq_ = value;
  }
  /**
   * <code>int64 minSeq = 13;</code>
   */
  private void clearMinSeq() {
    
    minSeq_ = 0L;
  }

  public static final int MAXSEQ_FIELD_NUMBER = 14;
  private long maxSeq_;
  /**
   * <code>int64 maxSeq = 14;</code>
   * @return The maxSeq.
   */
  @java.lang.Override
  public long getMaxSeq() {
    return maxSeq_;
  }
  /**
   * <code>int64 maxSeq = 14;</code>
   * @param value The maxSeq to set.
   */
  private void setMaxSeq(long value) {
    
    maxSeq_ = value;
  }
  /**
   * <code>int64 maxSeq = 14;</code>
   */
  private void clearMaxSeq() {
    
    maxSeq_ = 0L;
  }

  public static final int MSGDESTRUCTTIME_FIELD_NUMBER = 15;
  private long msgDestructTime_;
  /**
   * <code>int64 msgDestructTime = 15;</code>
   * @return The msgDestructTime.
   */
  @java.lang.Override
  public long getMsgDestructTime() {
    return msgDestructTime_;
  }
  /**
   * <code>int64 msgDestructTime = 15;</code>
   * @param value The msgDestructTime to set.
   */
  private void setMsgDestructTime(long value) {
    
    msgDestructTime_ = value;
  }
  /**
   * <code>int64 msgDestructTime = 15;</code>
   */
  private void clearMsgDestructTime() {
    
    msgDestructTime_ = 0L;
  }

  public static final int LATESTMSGDESTRUCTTIME_FIELD_NUMBER = 16;
  private long latestMsgDestructTime_;
  /**
   * <code>int64 latestMsgDestructTime = 16;</code>
   * @return The latestMsgDestructTime.
   */
  @java.lang.Override
  public long getLatestMsgDestructTime() {
    return latestMsgDestructTime_;
  }
  /**
   * <code>int64 latestMsgDestructTime = 16;</code>
   * @param value The latestMsgDestructTime to set.
   */
  private void setLatestMsgDestructTime(long value) {
    
    latestMsgDestructTime_ = value;
  }
  /**
   * <code>int64 latestMsgDestructTime = 16;</code>
   */
  private void clearLatestMsgDestructTime() {
    
    latestMsgDestructTime_ = 0L;
  }

  public static final int ISMSGDESTRUCT_FIELD_NUMBER = 17;
  private boolean isMsgDestruct_;
  /**
   * <code>bool isMsgDestruct = 17;</code>
   * @return The isMsgDestruct.
   */
  @java.lang.Override
  public boolean getIsMsgDestruct() {
    return isMsgDestruct_;
  }
  /**
   * <code>bool isMsgDestruct = 17;</code>
   * @param value The isMsgDestruct to set.
   */
  private void setIsMsgDestruct(boolean value) {
    
    isMsgDestruct_ = value;
  }
  /**
   * <code>bool isMsgDestruct = 17;</code>
   */
  private void clearIsMsgDestruct() {
    
    isMsgDestruct_ = false;
  }

  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.conversation.Conversation prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.conversation.Conversation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.conversation.Conversation, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.conversation.Conversation)
      io.openim.android.sdk.protos.conversation.ConversationOrBuilder {
    // Construct using io.openim.android.sdk.protos.conversation.Conversation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string ownerUserID = 1;</code>
     * @return The ownerUserID.
     */
    @java.lang.Override
    public java.lang.String getOwnerUserID() {
      return instance.getOwnerUserID();
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @return The bytes for ownerUserID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerUserIDBytes() {
      return instance.getOwnerUserIDBytes();
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @param value The ownerUserID to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setOwnerUserID(value);
      return this;
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerUserID() {
      copyOnWrite();
      instance.clearOwnerUserID();
      return this;
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @param value The bytes for ownerUserID to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOwnerUserIDBytes(value);
      return this;
    }

    /**
     * <code>string conversationID = 2;</code>
     * @return The conversationID.
     */
    @java.lang.Override
    public java.lang.String getConversationID() {
      return instance.getConversationID();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return The bytes for conversationID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIDBytes() {
      return instance.getConversationIDBytes();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationID(
        java.lang.String value) {
      copyOnWrite();
      instance.setConversationID(value);
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationID() {
      copyOnWrite();
      instance.clearConversationID();
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The bytes for conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConversationIDBytes(value);
      return this;
    }

    /**
     * <code>int32 recvMsgOpt = 3;</code>
     * @return The recvMsgOpt.
     */
    @java.lang.Override
    public int getRecvMsgOpt() {
      return instance.getRecvMsgOpt();
    }
    /**
     * <code>int32 recvMsgOpt = 3;</code>
     * @param value The recvMsgOpt to set.
     * @return This builder for chaining.
     */
    public Builder setRecvMsgOpt(int value) {
      copyOnWrite();
      instance.setRecvMsgOpt(value);
      return this;
    }
    /**
     * <code>int32 recvMsgOpt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecvMsgOpt() {
      copyOnWrite();
      instance.clearRecvMsgOpt();
      return this;
    }

    /**
     * <code>int32 conversationType = 4;</code>
     * @return The conversationType.
     */
    @java.lang.Override
    public int getConversationType() {
      return instance.getConversationType();
    }
    /**
     * <code>int32 conversationType = 4;</code>
     * @param value The conversationType to set.
     * @return This builder for chaining.
     */
    public Builder setConversationType(int value) {
      copyOnWrite();
      instance.setConversationType(value);
      return this;
    }
    /**
     * <code>int32 conversationType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationType() {
      copyOnWrite();
      instance.clearConversationType();
      return this;
    }

    /**
     * <code>string userID = 5;</code>
     * @return The userID.
     */
    @java.lang.Override
    public java.lang.String getUserID() {
      return instance.getUserID();
    }
    /**
     * <code>string userID = 5;</code>
     * @return The bytes for userID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      return instance.getUserIDBytes();
    }
    /**
     * <code>string userID = 5;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserID(value);
      return this;
    }
    /**
     * <code>string userID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      copyOnWrite();
      instance.clearUserID();
      return this;
    }
    /**
     * <code>string userID = 5;</code>
     * @param value The bytes for userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIDBytes(value);
      return this;
    }

    /**
     * <code>string groupID = 6;</code>
     * @return The groupID.
     */
    @java.lang.Override
    public java.lang.String getGroupID() {
      return instance.getGroupID();
    }
    /**
     * <code>string groupID = 6;</code>
     * @return The bytes for groupID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIDBytes() {
      return instance.getGroupIDBytes();
    }
    /**
     * <code>string groupID = 6;</code>
     * @param value The groupID to set.
     * @return This builder for chaining.
     */
    public Builder setGroupID(
        java.lang.String value) {
      copyOnWrite();
      instance.setGroupID(value);
      return this;
    }
    /**
     * <code>string groupID = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupID() {
      copyOnWrite();
      instance.clearGroupID();
      return this;
    }
    /**
     * <code>string groupID = 6;</code>
     * @param value The bytes for groupID to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGroupIDBytes(value);
      return this;
    }

    /**
     * <code>bool isPinned = 7;</code>
     * @return The isPinned.
     */
    @java.lang.Override
    public boolean getIsPinned() {
      return instance.getIsPinned();
    }
    /**
     * <code>bool isPinned = 7;</code>
     * @param value The isPinned to set.
     * @return This builder for chaining.
     */
    public Builder setIsPinned(boolean value) {
      copyOnWrite();
      instance.setIsPinned(value);
      return this;
    }
    /**
     * <code>bool isPinned = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPinned() {
      copyOnWrite();
      instance.clearIsPinned();
      return this;
    }

    /**
     * <code>string attachedInfo = 8;</code>
     * @return The attachedInfo.
     */
    @java.lang.Override
    public java.lang.String getAttachedInfo() {
      return instance.getAttachedInfo();
    }
    /**
     * <code>string attachedInfo = 8;</code>
     * @return The bytes for attachedInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttachedInfoBytes() {
      return instance.getAttachedInfoBytes();
    }
    /**
     * <code>string attachedInfo = 8;</code>
     * @param value The attachedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAttachedInfo(
        java.lang.String value) {
      copyOnWrite();
      instance.setAttachedInfo(value);
      return this;
    }
    /**
     * <code>string attachedInfo = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttachedInfo() {
      copyOnWrite();
      instance.clearAttachedInfo();
      return this;
    }
    /**
     * <code>string attachedInfo = 8;</code>
     * @param value The bytes for attachedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAttachedInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAttachedInfoBytes(value);
      return this;
    }

    /**
     * <code>bool isPrivateChat = 9;</code>
     * @return The isPrivateChat.
     */
    @java.lang.Override
    public boolean getIsPrivateChat() {
      return instance.getIsPrivateChat();
    }
    /**
     * <code>bool isPrivateChat = 9;</code>
     * @param value The isPrivateChat to set.
     * @return This builder for chaining.
     */
    public Builder setIsPrivateChat(boolean value) {
      copyOnWrite();
      instance.setIsPrivateChat(value);
      return this;
    }
    /**
     * <code>bool isPrivateChat = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPrivateChat() {
      copyOnWrite();
      instance.clearIsPrivateChat();
      return this;
    }

    /**
     * <code>int32 groupAtType = 10;</code>
     * @return The groupAtType.
     */
    @java.lang.Override
    public int getGroupAtType() {
      return instance.getGroupAtType();
    }
    /**
     * <code>int32 groupAtType = 10;</code>
     * @param value The groupAtType to set.
     * @return This builder for chaining.
     */
    public Builder setGroupAtType(int value) {
      copyOnWrite();
      instance.setGroupAtType(value);
      return this;
    }
    /**
     * <code>int32 groupAtType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupAtType() {
      copyOnWrite();
      instance.clearGroupAtType();
      return this;
    }

    /**
     * <code>string ex = 11;</code>
     * @return The ex.
     */
    @java.lang.Override
    public java.lang.String getEx() {
      return instance.getEx();
    }
    /**
     * <code>string ex = 11;</code>
     * @return The bytes for ex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExBytes() {
      return instance.getExBytes();
    }
    /**
     * <code>string ex = 11;</code>
     * @param value The ex to set.
     * @return This builder for chaining.
     */
    public Builder setEx(
        java.lang.String value) {
      copyOnWrite();
      instance.setEx(value);
      return this;
    }
    /**
     * <code>string ex = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEx() {
      copyOnWrite();
      instance.clearEx();
      return this;
    }
    /**
     * <code>string ex = 11;</code>
     * @param value The bytes for ex to set.
     * @return This builder for chaining.
     */
    public Builder setExBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExBytes(value);
      return this;
    }

    /**
     * <code>int32 burnDuration = 12;</code>
     * @return The burnDuration.
     */
    @java.lang.Override
    public int getBurnDuration() {
      return instance.getBurnDuration();
    }
    /**
     * <code>int32 burnDuration = 12;</code>
     * @param value The burnDuration to set.
     * @return This builder for chaining.
     */
    public Builder setBurnDuration(int value) {
      copyOnWrite();
      instance.setBurnDuration(value);
      return this;
    }
    /**
     * <code>int32 burnDuration = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBurnDuration() {
      copyOnWrite();
      instance.clearBurnDuration();
      return this;
    }

    /**
     * <code>int64 minSeq = 13;</code>
     * @return The minSeq.
     */
    @java.lang.Override
    public long getMinSeq() {
      return instance.getMinSeq();
    }
    /**
     * <code>int64 minSeq = 13;</code>
     * @param value The minSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMinSeq(long value) {
      copyOnWrite();
      instance.setMinSeq(value);
      return this;
    }
    /**
     * <code>int64 minSeq = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinSeq() {
      copyOnWrite();
      instance.clearMinSeq();
      return this;
    }

    /**
     * <code>int64 maxSeq = 14;</code>
     * @return The maxSeq.
     */
    @java.lang.Override
    public long getMaxSeq() {
      return instance.getMaxSeq();
    }
    /**
     * <code>int64 maxSeq = 14;</code>
     * @param value The maxSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSeq(long value) {
      copyOnWrite();
      instance.setMaxSeq(value);
      return this;
    }
    /**
     * <code>int64 maxSeq = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSeq() {
      copyOnWrite();
      instance.clearMaxSeq();
      return this;
    }

    /**
     * <code>int64 msgDestructTime = 15;</code>
     * @return The msgDestructTime.
     */
    @java.lang.Override
    public long getMsgDestructTime() {
      return instance.getMsgDestructTime();
    }
    /**
     * <code>int64 msgDestructTime = 15;</code>
     * @param value The msgDestructTime to set.
     * @return This builder for chaining.
     */
    public Builder setMsgDestructTime(long value) {
      copyOnWrite();
      instance.setMsgDestructTime(value);
      return this;
    }
    /**
     * <code>int64 msgDestructTime = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgDestructTime() {
      copyOnWrite();
      instance.clearMsgDestructTime();
      return this;
    }

    /**
     * <code>int64 latestMsgDestructTime = 16;</code>
     * @return The latestMsgDestructTime.
     */
    @java.lang.Override
    public long getLatestMsgDestructTime() {
      return instance.getLatestMsgDestructTime();
    }
    /**
     * <code>int64 latestMsgDestructTime = 16;</code>
     * @param value The latestMsgDestructTime to set.
     * @return This builder for chaining.
     */
    public Builder setLatestMsgDestructTime(long value) {
      copyOnWrite();
      instance.setLatestMsgDestructTime(value);
      return this;
    }
    /**
     * <code>int64 latestMsgDestructTime = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearLatestMsgDestructTime() {
      copyOnWrite();
      instance.clearLatestMsgDestructTime();
      return this;
    }

    /**
     * <code>bool isMsgDestruct = 17;</code>
     * @return The isMsgDestruct.
     */
    @java.lang.Override
    public boolean getIsMsgDestruct() {
      return instance.getIsMsgDestruct();
    }
    /**
     * <code>bool isMsgDestruct = 17;</code>
     * @param value The isMsgDestruct to set.
     * @return This builder for chaining.
     */
    public Builder setIsMsgDestruct(boolean value) {
      copyOnWrite();
      instance.setIsMsgDestruct(value);
      return this;
    }
    /**
     * <code>bool isMsgDestruct = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMsgDestruct() {
      copyOnWrite();
      instance.clearIsMsgDestruct();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.conversation.Conversation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.conversation.Conversation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ownerUserID_",
            "conversationID_",
            "recvMsgOpt_",
            "conversationType_",
            "userID_",
            "groupID_",
            "isPinned_",
            "attachedInfo_",
            "isPrivateChat_",
            "groupAtType_",
            "ex_",
            "burnDuration_",
            "minSeq_",
            "maxSeq_",
            "msgDestructTime_",
            "latestMsgDestructTime_",
            "isMsgDestruct_",
          };
          java.lang.String info =
              "\u0000\u0011\u0000\u0000\u0001\u0011\u0011\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0004\u0005\u0208\u0006\u0208\u0007\u0007\b\u0208\t\u0007\n\u0004" +
              "\u000b\u0208\f\u0004\r\u0002\u000e\u0002\u000f\u0002\u0010\u0002\u0011\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.conversation.Conversation> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.conversation.Conversation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.conversation.Conversation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.conversation.Conversation)
  private static final io.openim.android.sdk.protos.conversation.Conversation DEFAULT_INSTANCE;
  static {
    Conversation defaultInstance = new Conversation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Conversation.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.conversation.Conversation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Conversation> PARSER;

  public static com.google.protobuf.Parser<Conversation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

