// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/conversation.proto

package io.openim.android.sdk.protos.conversation;

public interface GetAllConversationsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.conversation.GetAllConversationsResp)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .openim.conversation.Conversation conversations = 2;</code>
   */
  java.util.List<io.openim.android.sdk.protos.conversation.Conversation> 
      getConversationsList();
  /**
   * <code>repeated .openim.conversation.Conversation conversations = 2;</code>
   */
  io.openim.android.sdk.protos.conversation.Conversation getConversations(int index);
  /**
   * <code>repeated .openim.conversation.Conversation conversations = 2;</code>
   */
  int getConversationsCount();
}
