// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/conversation.proto

package io.openim.android.sdk.protos.conversation;

public interface GetConversationsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.conversation.GetConversationsReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ownerUserID = 1;</code>
   * @return The ownerUserID.
   */
  java.lang.String getOwnerUserID();
  /**
   * <code>string ownerUserID = 1;</code>
   * @return The bytes for ownerUserID.
   */
  com.google.protobuf.ByteString
      getOwnerUserIDBytes();

  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @return A list containing the conversationIDs.
   */
  java.util.List<java.lang.String>
      getConversationIDsList();
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @return The count of conversationIDs.
   */
  int getConversationIDsCount();
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param index The index of the element to return.
   * @return The conversationIDs at the given index.
   */
  java.lang.String getConversationIDs(int index);
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param index The index of the element to return.
   * @return The conversationIDs at the given index.
   */
  com.google.protobuf.ByteString
      getConversationIDsBytes(int index);
}
