// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/conversation.proto

package io.openim.android.sdk.protos.conversation;

/**
 * Protobuf type {@code openim.conversation.GetConversationsReq}
 */
public  final class GetConversationsReq extends
    com.google.protobuf.GeneratedMessageLite<
        GetConversationsReq, GetConversationsReq.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.conversation.GetConversationsReq)
    GetConversationsReqOrBuilder {
  private GetConversationsReq() {
    ownerUserID_ = "";
    conversationIDs_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int OWNERUSERID_FIELD_NUMBER = 1;
  private java.lang.String ownerUserID_;
  /**
   * <code>string ownerUserID = 1;</code>
   * @return The ownerUserID.
   */
  @java.lang.Override
  public java.lang.String getOwnerUserID() {
    return ownerUserID_;
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @return The bytes for ownerUserID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ownerUserID_);
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @param value The ownerUserID to set.
   */
  private void setOwnerUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ownerUserID_ = value;
  }
  /**
   * <code>string ownerUserID = 1;</code>
   */
  private void clearOwnerUserID() {
    
    ownerUserID_ = getDefaultInstance().getOwnerUserID();
  }
  /**
   * <code>string ownerUserID = 1;</code>
   * @param value The bytes for ownerUserID to set.
   */
  private void setOwnerUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ownerUserID_ = value.toStringUtf8();
    
  }

  public static final int CONVERSATIONIDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> conversationIDs_;
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @return A list containing the conversationIDs.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getConversationIDsList() {
    return conversationIDs_;
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @return The count of conversationIDs.
   */
  @java.lang.Override
  public int getConversationIDsCount() {
    return conversationIDs_.size();
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param index The index of the element to return.
   * @return The conversationIDs at the given index.
   */
  @java.lang.Override
  public java.lang.String getConversationIDs(int index) {
    return conversationIDs_.get(index);
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the conversationIDs at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        conversationIDs_.get(index));
  }
  private void ensureConversationIDsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        conversationIDs_;  if (!tmp.isModifiable()) {
      conversationIDs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param index The index to set the value at.
   * @param value The conversationIDs to set.
   */
  private void setConversationIDs(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureConversationIDsIsMutable();
    conversationIDs_.set(index, value);
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param value The conversationIDs to add.
   */
  private void addConversationIDs(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureConversationIDsIsMutable();
    conversationIDs_.add(value);
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param values The conversationIDs to add.
   */
  private void addAllConversationIDs(
      java.lang.Iterable<java.lang.String> values) {
    ensureConversationIDsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, conversationIDs_);
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   */
  private void clearConversationIDs() {
    conversationIDs_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string conversationIDs = 2;</code>
   * @param value The bytes of the conversationIDs to add.
   */
  private void addConversationIDsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureConversationIDsIsMutable();
    conversationIDs_.add(value.toStringUtf8());
  }

  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.conversation.GetConversationsReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.conversation.GetConversationsReq prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.conversation.GetConversationsReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.conversation.GetConversationsReq, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.conversation.GetConversationsReq)
      io.openim.android.sdk.protos.conversation.GetConversationsReqOrBuilder {
    // Construct using io.openim.android.sdk.protos.conversation.GetConversationsReq.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string ownerUserID = 1;</code>
     * @return The ownerUserID.
     */
    @java.lang.Override
    public java.lang.String getOwnerUserID() {
      return instance.getOwnerUserID();
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @return The bytes for ownerUserID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerUserIDBytes() {
      return instance.getOwnerUserIDBytes();
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @param value The ownerUserID to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setOwnerUserID(value);
      return this;
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerUserID() {
      copyOnWrite();
      instance.clearOwnerUserID();
      return this;
    }
    /**
     * <code>string ownerUserID = 1;</code>
     * @param value The bytes for ownerUserID to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOwnerUserIDBytes(value);
      return this;
    }

    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @return A list containing the conversationIDs.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getConversationIDsList() {
      return java.util.Collections.unmodifiableList(
          instance.getConversationIDsList());
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @return The count of conversationIDs.
     */
    @java.lang.Override
    public int getConversationIDsCount() {
      return instance.getConversationIDsCount();
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param index The index of the element to return.
     * @return The conversationIDs at the given index.
     */
    @java.lang.Override
    public java.lang.String getConversationIDs(int index) {
      return instance.getConversationIDs(index);
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the conversationIDs at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIDsBytes(int index) {
      return instance.getConversationIDsBytes(index);
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param index The index to set the value at.
     * @param value The conversationIDs to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDs(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setConversationIDs(index, value);
      return this;
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param value The conversationIDs to add.
     * @return This builder for chaining.
     */
    public Builder addConversationIDs(
        java.lang.String value) {
      copyOnWrite();
      instance.addConversationIDs(value);
      return this;
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param values The conversationIDs to add.
     * @return This builder for chaining.
     */
    public Builder addAllConversationIDs(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllConversationIDs(values);
      return this;
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationIDs() {
      copyOnWrite();
      instance.clearConversationIDs();
      return this;
    }
    /**
     * <code>repeated string conversationIDs = 2;</code>
     * @param value The bytes of the conversationIDs to add.
     * @return This builder for chaining.
     */
    public Builder addConversationIDsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addConversationIDsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.conversation.GetConversationsReq)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.conversation.GetConversationsReq();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ownerUserID_",
            "conversationIDs_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u021a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.conversation.GetConversationsReq> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.conversation.GetConversationsReq.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.conversation.GetConversationsReq>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.conversation.GetConversationsReq)
  private static final io.openim.android.sdk.protos.conversation.GetConversationsReq DEFAULT_INSTANCE;
  static {
    GetConversationsReq defaultInstance = new GetConversationsReq();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetConversationsReq.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.conversation.GetConversationsReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetConversationsReq> PARSER;

  public static com.google.protobuf.Parser<GetConversationsReq> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

