// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

public interface GetConversationsHasReadAndMaxSeqRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.msg.GetConversationsHasReadAndMaxSeqResp)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>map&lt;string, .openim.msg.Seqs&gt; seqs = 1;</code>
   */
  int getSeqsCount();
  /**
   * <code>map&lt;string, .openim.msg.Seqs&gt; seqs = 1;</code>
   */
  boolean containsSeqs(
      java.lang.String key);
  /**
   * Use {@link #getSeqsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.openim.android.sdk.protos.msg.Seqs>
  getSeqs();
  /**
   * <code>map&lt;string, .openim.msg.Seqs&gt; seqs = 1;</code>
   */
  java.util.Map<java.lang.String, io.openim.android.sdk.protos.msg.Seqs>
  getSeqsMap();
  /**
   * <code>map&lt;string, .openim.msg.Seqs&gt; seqs = 1;</code>
   */

  /* nullable */
io.openim.android.sdk.protos.msg.Seqs getSeqsOrDefault(
      java.lang.String key,
      /* nullable */
io.openim.android.sdk.protos.msg.Seqs defaultValue);
  /**
   * <code>map&lt;string, .openim.msg.Seqs&gt; seqs = 1;</code>
   */

  io.openim.android.sdk.protos.msg.Seqs getSeqsOrThrow(
      java.lang.String key);
}
