// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

public interface MarkConversationAsReadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.msg.MarkConversationAsReadReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string conversationID = 1;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 1;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();

  /**
   * <code>string userID = 2;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 2;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>int64 hasReadSeq = 3;</code>
   * @return The hasReadSeq.
   */
  long getHasReadSeq();

  /**
   * <code>repeated int64 seqs = 4;</code>
   * @return A list containing the seqs.
   */
  java.util.List<java.lang.Long> getSeqsList();
  /**
   * <code>repeated int64 seqs = 4;</code>
   * @return The count of seqs.
   */
  int getSeqsCount();
  /**
   * <code>repeated int64 seqs = 4;</code>
   * @param index The index of the element to return.
   * @return The seqs at the given index.
   */
  long getSeqs(int index);
}
