// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

public interface MarkConversationAsReadRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.msg.MarkConversationAsReadResp)
    com.google.protobuf.MessageLiteOrBuilder {
}
