// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

/**
 * Protobuf type {@code openim.msg.Seqs}
 */
public  final class Seqs extends
    com.google.protobuf.GeneratedMessageLite<
        Seqs, Seqs.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.msg.Seqs)
    SeqsOrBuilder {
  private Seqs() {
  }
  public static final int MAXSEQ_FIELD_NUMBER = 1;
  private long maxSeq_;
  /**
   * <code>int64 maxSeq = 1;</code>
   * @return The maxSeq.
   */
  @java.lang.Override
  public long getMaxSeq() {
    return maxSeq_;
  }
  /**
   * <code>int64 maxSeq = 1;</code>
   * @param value The maxSeq to set.
   */
  private void setMaxSeq(long value) {
    
    maxSeq_ = value;
  }
  /**
   * <code>int64 maxSeq = 1;</code>
   */
  private void clearMaxSeq() {
    
    maxSeq_ = 0L;
  }

  public static final int HASREADSEQ_FIELD_NUMBER = 2;
  private long hasReadSeq_;
  /**
   * <code>int64 hasReadSeq = 2;</code>
   * @return The hasReadSeq.
   */
  @java.lang.Override
  public long getHasReadSeq() {
    return hasReadSeq_;
  }
  /**
   * <code>int64 hasReadSeq = 2;</code>
   * @param value The hasReadSeq to set.
   */
  private void setHasReadSeq(long value) {
    
    hasReadSeq_ = value;
  }
  /**
   * <code>int64 hasReadSeq = 2;</code>
   */
  private void clearHasReadSeq() {
    
    hasReadSeq_ = 0L;
  }

  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.msg.Seqs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.msg.Seqs prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.msg.Seqs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.msg.Seqs, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.msg.Seqs)
      io.openim.android.sdk.protos.msg.SeqsOrBuilder {
    // Construct using io.openim.android.sdk.protos.msg.Seqs.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 maxSeq = 1;</code>
     * @return The maxSeq.
     */
    @java.lang.Override
    public long getMaxSeq() {
      return instance.getMaxSeq();
    }
    /**
     * <code>int64 maxSeq = 1;</code>
     * @param value The maxSeq to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSeq(long value) {
      copyOnWrite();
      instance.setMaxSeq(value);
      return this;
    }
    /**
     * <code>int64 maxSeq = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSeq() {
      copyOnWrite();
      instance.clearMaxSeq();
      return this;
    }

    /**
     * <code>int64 hasReadSeq = 2;</code>
     * @return The hasReadSeq.
     */
    @java.lang.Override
    public long getHasReadSeq() {
      return instance.getHasReadSeq();
    }
    /**
     * <code>int64 hasReadSeq = 2;</code>
     * @param value The hasReadSeq to set.
     * @return This builder for chaining.
     */
    public Builder setHasReadSeq(long value) {
      copyOnWrite();
      instance.setHasReadSeq(value);
      return this;
    }
    /**
     * <code>int64 hasReadSeq = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasReadSeq() {
      copyOnWrite();
      instance.clearHasReadSeq();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.msg.Seqs)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.msg.Seqs();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "maxSeq_",
            "hasReadSeq_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.msg.Seqs> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.msg.Seqs.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.msg.Seqs>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.msg.Seqs)
  private static final io.openim.android.sdk.protos.msg.Seqs DEFAULT_INSTANCE;
  static {
    Seqs defaultInstance = new Seqs();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Seqs.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.msg.Seqs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Seqs> PARSER;

  public static com.google.protobuf.Parser<Seqs> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

