// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

public interface SeqsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.msg.Seqs)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 maxSeq = 1;</code>
   * @return The maxSeq.
   */
  long getMaxSeq();

  /**
   * <code>int64 hasReadSeq = 2;</code>
   * @return The hasReadSeq.
   */
  long getHasReadSeq();
}
