// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/msg.proto

package io.openim.android.sdk.protos.msg;

public interface SetConversationHasReadSeqReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.msg.SetConversationHasReadSeqReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string conversationID = 1;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 1;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();

  /**
   * <code>string userID = 2;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 2;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>int64 hasReadSeq = 3;</code>
   * @return The hasReadSeq.
   */
  long getHasReadSeq();
}
