// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface ConversationHasReadTipsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.ConversationHasReadTips)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string conversationID = 2;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 2;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();

  /**
   * <code>int64 hasReadSeq = 3;</code>
   * @return The hasReadSeq.
   */
  long getHasReadSeq();

  /**
   * <code>int64 unreadCountTime = 4;</code>
   * @return The unreadCountTime.
   */
  long getUnreadCountTime();
}
