// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.ConversationHasReadTips}
 */
public  final class ConversationHasReadTips extends
    com.google.protobuf.GeneratedMessageLite<
        ConversationHasReadTips, ConversationHasReadTips.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.ConversationHasReadTips)
    ConversationHasReadTipsOrBuilder {
  private ConversationHasReadTips() {
    userID_ = "";
    conversationID_ = "";
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.String userID_;
  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  @java.lang.Override
  public java.lang.String getUserID() {
    return userID_;
  }
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userID_);
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The userID to set.
   */
  private void setUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userID_ = value;
  }
  /**
   * <code>string userID = 1;</code>
   */
  private void clearUserID() {
    
    userID_ = getDefaultInstance().getUserID();
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The bytes for userID to set.
   */
  private void setUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userID_ = value.toStringUtf8();
    
  }

  public static final int CONVERSATIONID_FIELD_NUMBER = 2;
  private java.lang.String conversationID_;
  /**
   * <code>string conversationID = 2;</code>
   * @return The conversationID.
   */
  @java.lang.Override
  public java.lang.String getConversationID() {
    return conversationID_;
  }
  /**
   * <code>string conversationID = 2;</code>
   * @return The bytes for conversationID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conversationID_);
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The conversationID to set.
   */
  private void setConversationID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    conversationID_ = value;
  }
  /**
   * <code>string conversationID = 2;</code>
   */
  private void clearConversationID() {
    
    conversationID_ = getDefaultInstance().getConversationID();
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The bytes for conversationID to set.
   */
  private void setConversationIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conversationID_ = value.toStringUtf8();
    
  }

  public static final int HASREADSEQ_FIELD_NUMBER = 3;
  private long hasReadSeq_;
  /**
   * <code>int64 hasReadSeq = 3;</code>
   * @return The hasReadSeq.
   */
  @java.lang.Override
  public long getHasReadSeq() {
    return hasReadSeq_;
  }
  /**
   * <code>int64 hasReadSeq = 3;</code>
   * @param value The hasReadSeq to set.
   */
  private void setHasReadSeq(long value) {
    
    hasReadSeq_ = value;
  }
  /**
   * <code>int64 hasReadSeq = 3;</code>
   */
  private void clearHasReadSeq() {
    
    hasReadSeq_ = 0L;
  }

  public static final int UNREADCOUNTTIME_FIELD_NUMBER = 4;
  private long unreadCountTime_;
  /**
   * <code>int64 unreadCountTime = 4;</code>
   * @return The unreadCountTime.
   */
  @java.lang.Override
  public long getUnreadCountTime() {
    return unreadCountTime_;
  }
  /**
   * <code>int64 unreadCountTime = 4;</code>
   * @param value The unreadCountTime to set.
   */
  private void setUnreadCountTime(long value) {
    
    unreadCountTime_ = value;
  }
  /**
   * <code>int64 unreadCountTime = 4;</code>
   */
  private void clearUnreadCountTime() {
    
    unreadCountTime_ = 0L;
  }

  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.ConversationHasReadTips prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.ConversationHasReadTips}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.ConversationHasReadTips, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.ConversationHasReadTips)
      io.openim.android.sdk.protos.sdkws.ConversationHasReadTipsOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.ConversationHasReadTips.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string userID = 1;</code>
     * @return The userID.
     */
    @java.lang.Override
    public java.lang.String getUserID() {
      return instance.getUserID();
    }
    /**
     * <code>string userID = 1;</code>
     * @return The bytes for userID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      return instance.getUserIDBytes();
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserID(value);
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      copyOnWrite();
      instance.clearUserID();
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The bytes for userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIDBytes(value);
      return this;
    }

    /**
     * <code>string conversationID = 2;</code>
     * @return The conversationID.
     */
    @java.lang.Override
    public java.lang.String getConversationID() {
      return instance.getConversationID();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return The bytes for conversationID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIDBytes() {
      return instance.getConversationIDBytes();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationID(
        java.lang.String value) {
      copyOnWrite();
      instance.setConversationID(value);
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationID() {
      copyOnWrite();
      instance.clearConversationID();
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The bytes for conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConversationIDBytes(value);
      return this;
    }

    /**
     * <code>int64 hasReadSeq = 3;</code>
     * @return The hasReadSeq.
     */
    @java.lang.Override
    public long getHasReadSeq() {
      return instance.getHasReadSeq();
    }
    /**
     * <code>int64 hasReadSeq = 3;</code>
     * @param value The hasReadSeq to set.
     * @return This builder for chaining.
     */
    public Builder setHasReadSeq(long value) {
      copyOnWrite();
      instance.setHasReadSeq(value);
      return this;
    }
    /**
     * <code>int64 hasReadSeq = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasReadSeq() {
      copyOnWrite();
      instance.clearHasReadSeq();
      return this;
    }

    /**
     * <code>int64 unreadCountTime = 4;</code>
     * @return The unreadCountTime.
     */
    @java.lang.Override
    public long getUnreadCountTime() {
      return instance.getUnreadCountTime();
    }
    /**
     * <code>int64 unreadCountTime = 4;</code>
     * @param value The unreadCountTime to set.
     * @return This builder for chaining.
     */
    public Builder setUnreadCountTime(long value) {
      copyOnWrite();
      instance.setUnreadCountTime(value);
      return this;
    }
    /**
     * <code>int64 unreadCountTime = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnreadCountTime() {
      copyOnWrite();
      instance.clearUnreadCountTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.ConversationHasReadTips)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.ConversationHasReadTips();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userID_",
            "conversationID_",
            "hasReadSeq_",
            "unreadCountTime_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0002\u0004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.ConversationHasReadTips> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.ConversationHasReadTips.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.ConversationHasReadTips>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.ConversationHasReadTips)
  private static final io.openim.android.sdk.protos.sdkws.ConversationHasReadTips DEFAULT_INSTANCE;
  static {
    ConversationHasReadTips defaultInstance = new ConversationHasReadTips();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ConversationHasReadTips.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.ConversationHasReadTips getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ConversationHasReadTips> PARSER;

  public static com.google.protobuf.Parser<ConversationHasReadTips> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

