// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface ConversationUpdateTipsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.ConversationUpdateTips)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>repeated string conversationIDList = 2;</code>
   * @return A list containing the conversationIDList.
   */
  java.util.List<java.lang.String>
      getConversationIDListList();
  /**
   * <code>repeated string conversationIDList = 2;</code>
   * @return The count of conversationIDList.
   */
  int getConversationIDListCount();
  /**
   * <code>repeated string conversationIDList = 2;</code>
   * @param index The index of the element to return.
   * @return The conversationIDList at the given index.
   */
  java.lang.String getConversationIDList(int index);
  /**
   * <code>repeated string conversationIDList = 2;</code>
   * @param index The index of the element to return.
   * @return The conversationIDList at the given index.
   */
  com.google.protobuf.ByteString
      getConversationIDListBytes(int index);
}
