// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.DeleteMsgsTips}
 */
public  final class DeleteMsgsTips extends
    com.google.protobuf.GeneratedMessageLite<
        DeleteMsgsTips, DeleteMsgsTips.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.DeleteMsgsTips)
    DeleteMsgsTipsOrBuilder {
  private DeleteMsgsTips() {
    userID_ = "";
    conversationID_ = "";
    seqs_ = emptyLongList();
  }
  public static final int USERID_FIELD_NUMBER = 1;
  private java.lang.String userID_;
  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  @java.lang.Override
  public java.lang.String getUserID() {
    return userID_;
  }
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userID_);
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The userID to set.
   */
  private void setUserID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userID_ = value;
  }
  /**
   * <code>string userID = 1;</code>
   */
  private void clearUserID() {
    
    userID_ = getDefaultInstance().getUserID();
  }
  /**
   * <code>string userID = 1;</code>
   * @param value The bytes for userID to set.
   */
  private void setUserIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userID_ = value.toStringUtf8();
    
  }

  public static final int CONVERSATIONID_FIELD_NUMBER = 2;
  private java.lang.String conversationID_;
  /**
   * <code>string conversationID = 2;</code>
   * @return The conversationID.
   */
  @java.lang.Override
  public java.lang.String getConversationID() {
    return conversationID_;
  }
  /**
   * <code>string conversationID = 2;</code>
   * @return The bytes for conversationID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conversationID_);
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The conversationID to set.
   */
  private void setConversationID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    conversationID_ = value;
  }
  /**
   * <code>string conversationID = 2;</code>
   */
  private void clearConversationID() {
    
    conversationID_ = getDefaultInstance().getConversationID();
  }
  /**
   * <code>string conversationID = 2;</code>
   * @param value The bytes for conversationID to set.
   */
  private void setConversationIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conversationID_ = value.toStringUtf8();
    
  }

  public static final int SEQS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList seqs_;
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @return A list containing the seqs.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getSeqsList() {
    return seqs_;
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @return The count of seqs.
   */
  @java.lang.Override
  public int getSeqsCount() {
    return seqs_.size();
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @param index The index of the element to return.
   * @return The seqs at the given index.
   */
  @java.lang.Override
  public long getSeqs(int index) {
    return seqs_.getLong(index);
  }
  private int seqsMemoizedSerializedSize = -1;
  private void ensureSeqsIsMutable() {
    com.google.protobuf.Internal.LongList tmp = seqs_;
    if (!tmp.isModifiable()) {
      seqs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @param index The index to set the value at.
   * @param value The seqs to set.
   */
  private void setSeqs(
      int index, long value) {
    ensureSeqsIsMutable();
    seqs_.setLong(index, value);
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @param value The seqs to add.
   */
  private void addSeqs(long value) {
    ensureSeqsIsMutable();
    seqs_.addLong(value);
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   * @param values The seqs to add.
   */
  private void addAllSeqs(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureSeqsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, seqs_);
  }
  /**
   * <code>repeated int64 seqs = 3;</code>
   */
  private void clearSeqs() {
    seqs_ = emptyLongList();
  }

  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.DeleteMsgsTips prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.DeleteMsgsTips}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.DeleteMsgsTips, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.DeleteMsgsTips)
      io.openim.android.sdk.protos.sdkws.DeleteMsgsTipsOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.DeleteMsgsTips.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string userID = 1;</code>
     * @return The userID.
     */
    @java.lang.Override
    public java.lang.String getUserID() {
      return instance.getUserID();
    }
    /**
     * <code>string userID = 1;</code>
     * @return The bytes for userID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIDBytes() {
      return instance.getUserIDBytes();
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserID(value);
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      copyOnWrite();
      instance.clearUserID();
      return this;
    }
    /**
     * <code>string userID = 1;</code>
     * @param value The bytes for userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIDBytes(value);
      return this;
    }

    /**
     * <code>string conversationID = 2;</code>
     * @return The conversationID.
     */
    @java.lang.Override
    public java.lang.String getConversationID() {
      return instance.getConversationID();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return The bytes for conversationID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIDBytes() {
      return instance.getConversationIDBytes();
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationID(
        java.lang.String value) {
      copyOnWrite();
      instance.setConversationID(value);
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationID() {
      copyOnWrite();
      instance.clearConversationID();
      return this;
    }
    /**
     * <code>string conversationID = 2;</code>
     * @param value The bytes for conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConversationIDBytes(value);
      return this;
    }

    /**
     * <code>repeated int64 seqs = 3;</code>
     * @return A list containing the seqs.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getSeqsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSeqsList());
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @return The count of seqs.
     */
    @java.lang.Override
    public int getSeqsCount() {
      return instance.getSeqsCount();
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @param index The index of the element to return.
     * @return The seqs at the given index.
     */
    @java.lang.Override
    public long getSeqs(int index) {
      return instance.getSeqs(index);
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @param value The seqs to set.
     * @return This builder for chaining.
     */
    public Builder setSeqs(
        int index, long value) {
      copyOnWrite();
      instance.setSeqs(index, value);
      return this;
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @param value The seqs to add.
     * @return This builder for chaining.
     */
    public Builder addSeqs(long value) {
      copyOnWrite();
      instance.addSeqs(value);
      return this;
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @param values The seqs to add.
     * @return This builder for chaining.
     */
    public Builder addAllSeqs(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllSeqs(values);
      return this;
    }
    /**
     * <code>repeated int64 seqs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqs() {
      copyOnWrite();
      instance.clearSeqs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.DeleteMsgsTips)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.DeleteMsgsTips();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userID_",
            "conversationID_",
            "seqs_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003%";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.DeleteMsgsTips> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.DeleteMsgsTips.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.DeleteMsgsTips>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.DeleteMsgsTips)
  private static final io.openim.android.sdk.protos.sdkws.DeleteMsgsTips DEFAULT_INSTANCE;
  static {
    DeleteMsgsTips defaultInstance = new DeleteMsgsTips();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeleteMsgsTips.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.DeleteMsgsTips getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeleteMsgsTips> PARSER;

  public static com.google.protobuf.Parser<DeleteMsgsTips> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

