// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.GetMaxSeqResp}
 */
public  final class GetMaxSeqResp extends
    com.google.protobuf.GeneratedMessageLite<
        GetMaxSeqResp, GetMaxSeqResp.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.GetMaxSeqResp)
    GetMaxSeqRespOrBuilder {
  private GetMaxSeqResp() {
  }
  public static final int MAXSEQS_FIELD_NUMBER = 1;
  private static final class MaxSeqsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Long> maxSeqs_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMaxSeqs() {
    return maxSeqs_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMutableMaxSeqs() {
    if (!maxSeqs_.isMutable()) {
      maxSeqs_ = maxSeqs_.mutableCopy();
    }
    return maxSeqs_;
  }
  @java.lang.Override

  public int getMaxSeqsCount() {
    return internalGetMaxSeqs().size();
  }
  /**
   * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
   */
  @java.lang.Override

  public boolean containsMaxSeqs(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetMaxSeqs().containsKey(key);
  }
  /**
   * Use {@link #getMaxSeqsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getMaxSeqs() {
    return getMaxSeqsMap();
  }
  /**
   * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getMaxSeqsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetMaxSeqs());
  }
  /**
   * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
   */
  @java.lang.Override

  public long getMaxSeqsOrDefault(
      java.lang.String key,
      long defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMaxSeqs();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
   */
  @java.lang.Override

  public long getMaxSeqsOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMaxSeqs();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Long>
  getMutableMaxSeqsMap() {
    return internalGetMutableMaxSeqs();
  }

  public static final int MINSEQS_FIELD_NUMBER = 2;
  private static final class MinSeqsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Long> minSeqs_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMinSeqs() {
    return minSeqs_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMutableMinSeqs() {
    if (!minSeqs_.isMutable()) {
      minSeqs_ = minSeqs_.mutableCopy();
    }
    return minSeqs_;
  }
  @java.lang.Override

  public int getMinSeqsCount() {
    return internalGetMinSeqs().size();
  }
  /**
   * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
   */
  @java.lang.Override

  public boolean containsMinSeqs(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetMinSeqs().containsKey(key);
  }
  /**
   * Use {@link #getMinSeqsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getMinSeqs() {
    return getMinSeqsMap();
  }
  /**
   * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getMinSeqsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetMinSeqs());
  }
  /**
   * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
   */
  @java.lang.Override

  public long getMinSeqsOrDefault(
      java.lang.String key,
      long defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMinSeqs();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
   */
  @java.lang.Override

  public long getMinSeqsOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMinSeqs();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Long>
  getMutableMinSeqsMap() {
    return internalGetMutableMinSeqs();
  }

  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.GetMaxSeqResp prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.GetMaxSeqResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.GetMaxSeqResp, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.GetMaxSeqResp)
      io.openim.android.sdk.protos.sdkws.GetMaxSeqRespOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.GetMaxSeqResp.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    @java.lang.Override

    public int getMaxSeqsCount() {
      return instance.getMaxSeqsMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    @java.lang.Override

    public boolean containsMaxSeqs(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getMaxSeqsMap().containsKey(key);
    }

    public Builder clearMaxSeqs() {
      copyOnWrite();
      instance.getMutableMaxSeqsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */

    public Builder removeMaxSeqs(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableMaxSeqsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getMaxSeqsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getMaxSeqs() {
      return getMaxSeqsMap();
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getMaxSeqsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getMaxSeqsMap());
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    @java.lang.Override

    public long getMaxSeqsOrDefault(
        java.lang.String key,
        long defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getMaxSeqsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    @java.lang.Override

    public long getMaxSeqsOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getMaxSeqsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    public Builder putMaxSeqs(
        java.lang.String key,
        long value) {
      java.lang.Class<?> keyClass = key.getClass();
      
      copyOnWrite();
      instance.getMutableMaxSeqsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; maxSeqs = 1;</code>
     */
    public Builder putAllMaxSeqs(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      copyOnWrite();
      instance.getMutableMaxSeqsMap().putAll(values);
      return this;
    }

    @java.lang.Override

    public int getMinSeqsCount() {
      return instance.getMinSeqsMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    @java.lang.Override

    public boolean containsMinSeqs(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getMinSeqsMap().containsKey(key);
    }

    public Builder clearMinSeqs() {
      copyOnWrite();
      instance.getMutableMinSeqsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */

    public Builder removeMinSeqs(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableMinSeqsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getMinSeqsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getMinSeqs() {
      return getMinSeqsMap();
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getMinSeqsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getMinSeqsMap());
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    @java.lang.Override

    public long getMinSeqsOrDefault(
        java.lang.String key,
        long defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getMinSeqsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    @java.lang.Override

    public long getMinSeqsOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getMinSeqsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    public Builder putMinSeqs(
        java.lang.String key,
        long value) {
      java.lang.Class<?> keyClass = key.getClass();
      
      copyOnWrite();
      instance.getMutableMinSeqsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; minSeqs = 2;</code>
     */
    public Builder putAllMinSeqs(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      copyOnWrite();
      instance.getMutableMinSeqsMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.GetMaxSeqResp)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.GetMaxSeqResp();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "maxSeqs_",
            MaxSeqsDefaultEntryHolder.defaultEntry,
            "minSeqs_",
            MinSeqsDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0002\u0000\u0000\u00012\u00022";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.GetMaxSeqResp> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.GetMaxSeqResp.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.GetMaxSeqResp>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.GetMaxSeqResp)
  private static final io.openim.android.sdk.protos.sdkws.GetMaxSeqResp DEFAULT_INSTANCE;
  static {
    GetMaxSeqResp defaultInstance = new GetMaxSeqResp();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetMaxSeqResp.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.GetMaxSeqResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetMaxSeqResp> PARSER;

  public static com.google.protobuf.Parser<GetMaxSeqResp> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

