// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.MsgData}
 */
public  final class MsgData extends
    com.google.protobuf.GeneratedMessageLite<
        MsgData, MsgData.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.MsgData)
    MsgDataOrBuilder {
  private MsgData() {
    sendID_ = "";
    recvID_ = "";
    groupID_ = "";
    clientMsgID_ = "";
    serverMsgID_ = "";
    senderNickname_ = "";
    senderFaceURL_ = "";
    content_ = com.google.protobuf.ByteString.EMPTY;
    atUserIDList_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    attachedInfo_ = "";
    ex_ = "";
  }
  public static final int SENDID_FIELD_NUMBER = 1;
  private java.lang.String sendID_;
  /**
   * <code>string sendID = 1;</code>
   * @return The sendID.
   */
  @java.lang.Override
  public java.lang.String getSendID() {
    return sendID_;
  }
  /**
   * <code>string sendID = 1;</code>
   * @return The bytes for sendID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSendIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sendID_);
  }
  /**
   * <code>string sendID = 1;</code>
   * @param value The sendID to set.
   */
  private void setSendID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    sendID_ = value;
  }
  /**
   * <code>string sendID = 1;</code>
   */
  private void clearSendID() {
    
    sendID_ = getDefaultInstance().getSendID();
  }
  /**
   * <code>string sendID = 1;</code>
   * @param value The bytes for sendID to set.
   */
  private void setSendIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sendID_ = value.toStringUtf8();
    
  }

  public static final int RECVID_FIELD_NUMBER = 2;
  private java.lang.String recvID_;
  /**
   * <code>string recvID = 2;</code>
   * @return The recvID.
   */
  @java.lang.Override
  public java.lang.String getRecvID() {
    return recvID_;
  }
  /**
   * <code>string recvID = 2;</code>
   * @return The bytes for recvID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecvIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(recvID_);
  }
  /**
   * <code>string recvID = 2;</code>
   * @param value The recvID to set.
   */
  private void setRecvID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    recvID_ = value;
  }
  /**
   * <code>string recvID = 2;</code>
   */
  private void clearRecvID() {
    
    recvID_ = getDefaultInstance().getRecvID();
  }
  /**
   * <code>string recvID = 2;</code>
   * @param value The bytes for recvID to set.
   */
  private void setRecvIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    recvID_ = value.toStringUtf8();
    
  }

  public static final int GROUPID_FIELD_NUMBER = 3;
  private java.lang.String groupID_;
  /**
   * <code>string groupID = 3;</code>
   * @return The groupID.
   */
  @java.lang.Override
  public java.lang.String getGroupID() {
    return groupID_;
  }
  /**
   * <code>string groupID = 3;</code>
   * @return The bytes for groupID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(groupID_);
  }
  /**
   * <code>string groupID = 3;</code>
   * @param value The groupID to set.
   */
  private void setGroupID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    groupID_ = value;
  }
  /**
   * <code>string groupID = 3;</code>
   */
  private void clearGroupID() {
    
    groupID_ = getDefaultInstance().getGroupID();
  }
  /**
   * <code>string groupID = 3;</code>
   * @param value The bytes for groupID to set.
   */
  private void setGroupIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    groupID_ = value.toStringUtf8();
    
  }

  public static final int CLIENTMSGID_FIELD_NUMBER = 4;
  private java.lang.String clientMsgID_;
  /**
   * <code>string clientMsgID = 4;</code>
   * @return The clientMsgID.
   */
  @java.lang.Override
  public java.lang.String getClientMsgID() {
    return clientMsgID_;
  }
  /**
   * <code>string clientMsgID = 4;</code>
   * @return The bytes for clientMsgID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientMsgIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientMsgID_);
  }
  /**
   * <code>string clientMsgID = 4;</code>
   * @param value The clientMsgID to set.
   */
  private void setClientMsgID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientMsgID_ = value;
  }
  /**
   * <code>string clientMsgID = 4;</code>
   */
  private void clearClientMsgID() {
    
    clientMsgID_ = getDefaultInstance().getClientMsgID();
  }
  /**
   * <code>string clientMsgID = 4;</code>
   * @param value The bytes for clientMsgID to set.
   */
  private void setClientMsgIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientMsgID_ = value.toStringUtf8();
    
  }

  public static final int SERVERMSGID_FIELD_NUMBER = 5;
  private java.lang.String serverMsgID_;
  /**
   * <code>string serverMsgID = 5;</code>
   * @return The serverMsgID.
   */
  @java.lang.Override
  public java.lang.String getServerMsgID() {
    return serverMsgID_;
  }
  /**
   * <code>string serverMsgID = 5;</code>
   * @return The bytes for serverMsgID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerMsgIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverMsgID_);
  }
  /**
   * <code>string serverMsgID = 5;</code>
   * @param value The serverMsgID to set.
   */
  private void setServerMsgID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    serverMsgID_ = value;
  }
  /**
   * <code>string serverMsgID = 5;</code>
   */
  private void clearServerMsgID() {
    
    serverMsgID_ = getDefaultInstance().getServerMsgID();
  }
  /**
   * <code>string serverMsgID = 5;</code>
   * @param value The bytes for serverMsgID to set.
   */
  private void setServerMsgIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    serverMsgID_ = value.toStringUtf8();
    
  }

  public static final int SENDERPLATFORMID_FIELD_NUMBER = 6;
  private int senderPlatformID_;
  /**
   * <code>int32 senderPlatformID = 6;</code>
   * @return The senderPlatformID.
   */
  @java.lang.Override
  public int getSenderPlatformID() {
    return senderPlatformID_;
  }
  /**
   * <code>int32 senderPlatformID = 6;</code>
   * @param value The senderPlatformID to set.
   */
  private void setSenderPlatformID(int value) {
    
    senderPlatformID_ = value;
  }
  /**
   * <code>int32 senderPlatformID = 6;</code>
   */
  private void clearSenderPlatformID() {
    
    senderPlatformID_ = 0;
  }

  public static final int SENDERNICKNAME_FIELD_NUMBER = 7;
  private java.lang.String senderNickname_;
  /**
   * <code>string senderNickname = 7;</code>
   * @return The senderNickname.
   */
  @java.lang.Override
  public java.lang.String getSenderNickname() {
    return senderNickname_;
  }
  /**
   * <code>string senderNickname = 7;</code>
   * @return The bytes for senderNickname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderNicknameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderNickname_);
  }
  /**
   * <code>string senderNickname = 7;</code>
   * @param value The senderNickname to set.
   */
  private void setSenderNickname(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    senderNickname_ = value;
  }
  /**
   * <code>string senderNickname = 7;</code>
   */
  private void clearSenderNickname() {
    
    senderNickname_ = getDefaultInstance().getSenderNickname();
  }
  /**
   * <code>string senderNickname = 7;</code>
   * @param value The bytes for senderNickname to set.
   */
  private void setSenderNicknameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderNickname_ = value.toStringUtf8();
    
  }

  public static final int SENDERFACEURL_FIELD_NUMBER = 8;
  private java.lang.String senderFaceURL_;
  /**
   * <code>string senderFaceURL = 8;</code>
   * @return The senderFaceURL.
   */
  @java.lang.Override
  public java.lang.String getSenderFaceURL() {
    return senderFaceURL_;
  }
  /**
   * <code>string senderFaceURL = 8;</code>
   * @return The bytes for senderFaceURL.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderFaceURLBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderFaceURL_);
  }
  /**
   * <code>string senderFaceURL = 8;</code>
   * @param value The senderFaceURL to set.
   */
  private void setSenderFaceURL(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    senderFaceURL_ = value;
  }
  /**
   * <code>string senderFaceURL = 8;</code>
   */
  private void clearSenderFaceURL() {
    
    senderFaceURL_ = getDefaultInstance().getSenderFaceURL();
  }
  /**
   * <code>string senderFaceURL = 8;</code>
   * @param value The bytes for senderFaceURL to set.
   */
  private void setSenderFaceURLBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderFaceURL_ = value.toStringUtf8();
    
  }

  public static final int SESSIONTYPE_FIELD_NUMBER = 9;
  private int sessionType_;
  /**
   * <code>int32 sessionType = 9;</code>
   * @return The sessionType.
   */
  @java.lang.Override
  public int getSessionType() {
    return sessionType_;
  }
  /**
   * <code>int32 sessionType = 9;</code>
   * @param value The sessionType to set.
   */
  private void setSessionType(int value) {
    
    sessionType_ = value;
  }
  /**
   * <code>int32 sessionType = 9;</code>
   */
  private void clearSessionType() {
    
    sessionType_ = 0;
  }

  public static final int MSGFROM_FIELD_NUMBER = 10;
  private int msgFrom_;
  /**
   * <code>int32 msgFrom = 10;</code>
   * @return The msgFrom.
   */
  @java.lang.Override
  public int getMsgFrom() {
    return msgFrom_;
  }
  /**
   * <code>int32 msgFrom = 10;</code>
   * @param value The msgFrom to set.
   */
  private void setMsgFrom(int value) {
    
    msgFrom_ = value;
  }
  /**
   * <code>int32 msgFrom = 10;</code>
   */
  private void clearMsgFrom() {
    
    msgFrom_ = 0;
  }

  public static final int CONTENTTYPE_FIELD_NUMBER = 11;
  private int contentType_;
  /**
   * <code>int32 contentType = 11;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public int getContentType() {
    return contentType_;
  }
  /**
   * <code>int32 contentType = 11;</code>
   * @param value The contentType to set.
   */
  private void setContentType(int value) {
    
    contentType_ = value;
  }
  /**
   * <code>int32 contentType = 11;</code>
   */
  private void clearContentType() {
    
    contentType_ = 0;
  }

  public static final int CONTENT_FIELD_NUMBER = 12;
  private com.google.protobuf.ByteString content_;
  /**
   * <code>bytes content = 12;</code>
   * @return The content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getContent() {
    return content_;
  }
  /**
   * <code>bytes content = 12;</code>
   * @param value The content to set.
   */
  private void setContent(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    content_ = value;
  }
  /**
   * <code>bytes content = 12;</code>
   */
  private void clearContent() {
    
    content_ = getDefaultInstance().getContent();
  }

  public static final int SEQ_FIELD_NUMBER = 14;
  private long seq_;
  /**
   * <code>int64 seq = 14;</code>
   * @return The seq.
   */
  @java.lang.Override
  public long getSeq() {
    return seq_;
  }
  /**
   * <code>int64 seq = 14;</code>
   * @param value The seq to set.
   */
  private void setSeq(long value) {
    
    seq_ = value;
  }
  /**
   * <code>int64 seq = 14;</code>
   */
  private void clearSeq() {
    
    seq_ = 0L;
  }

  public static final int SENDTIME_FIELD_NUMBER = 15;
  private long sendTime_;
  /**
   * <code>int64 sendTime = 15;</code>
   * @return The sendTime.
   */
  @java.lang.Override
  public long getSendTime() {
    return sendTime_;
  }
  /**
   * <code>int64 sendTime = 15;</code>
   * @param value The sendTime to set.
   */
  private void setSendTime(long value) {
    
    sendTime_ = value;
  }
  /**
   * <code>int64 sendTime = 15;</code>
   */
  private void clearSendTime() {
    
    sendTime_ = 0L;
  }

  public static final int CREATETIME_FIELD_NUMBER = 16;
  private long createTime_;
  /**
   * <code>int64 createTime = 16;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public long getCreateTime() {
    return createTime_;
  }
  /**
   * <code>int64 createTime = 16;</code>
   * @param value The createTime to set.
   */
  private void setCreateTime(long value) {
    
    createTime_ = value;
  }
  /**
   * <code>int64 createTime = 16;</code>
   */
  private void clearCreateTime() {
    
    createTime_ = 0L;
  }

  public static final int STATUS_FIELD_NUMBER = 17;
  private int status_;
  /**
   * <code>int32 status = 17;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }
  /**
   * <code>int32 status = 17;</code>
   * @param value The status to set.
   */
  private void setStatus(int value) {
    
    status_ = value;
  }
  /**
   * <code>int32 status = 17;</code>
   */
  private void clearStatus() {
    
    status_ = 0;
  }

  public static final int ISREAD_FIELD_NUMBER = 18;
  private boolean isRead_;
  /**
   * <code>bool isRead = 18;</code>
   * @return The isRead.
   */
  @java.lang.Override
  public boolean getIsRead() {
    return isRead_;
  }
  /**
   * <code>bool isRead = 18;</code>
   * @param value The isRead to set.
   */
  private void setIsRead(boolean value) {
    
    isRead_ = value;
  }
  /**
   * <code>bool isRead = 18;</code>
   */
  private void clearIsRead() {
    
    isRead_ = false;
  }

  public static final int OPTIONS_FIELD_NUMBER = 19;
  private static final class OptionsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Boolean> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BOOL,
                false);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Boolean> options_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Boolean>
  internalGetOptions() {
    return options_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Boolean>
  internalGetMutableOptions() {
    if (!options_.isMutable()) {
      options_ = options_.mutableCopy();
    }
    return options_;
  }
  @java.lang.Override

  public int getOptionsCount() {
    return internalGetOptions().size();
  }
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  @java.lang.Override

  public boolean containsOptions(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetOptions().containsKey(key);
  }
  /**
   * Use {@link #getOptionsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Boolean> getOptions() {
    return getOptionsMap();
  }
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Boolean> getOptionsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetOptions());
  }
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  @java.lang.Override

  public boolean getOptionsOrDefault(
      java.lang.String key,
      boolean defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetOptions();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  @java.lang.Override

  public boolean getOptionsOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetOptions();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Boolean>
  getMutableOptionsMap() {
    return internalGetMutableOptions();
  }

  public static final int OFFLINEPUSHINFO_FIELD_NUMBER = 20;
  private io.openim.android.sdk.protos.sdkws.OfflinePushInfo offlinePushInfo_;
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   */
  @java.lang.Override
  public boolean hasOfflinePushInfo() {
    return offlinePushInfo_ != null;
  }
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   */
  @java.lang.Override
  public io.openim.android.sdk.protos.sdkws.OfflinePushInfo getOfflinePushInfo() {
    return offlinePushInfo_ == null ? io.openim.android.sdk.protos.sdkws.OfflinePushInfo.getDefaultInstance() : offlinePushInfo_;
  }
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   */
  private void setOfflinePushInfo(io.openim.android.sdk.protos.sdkws.OfflinePushInfo value) {
    value.getClass();
  offlinePushInfo_ = value;
    
    }
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeOfflinePushInfo(io.openim.android.sdk.protos.sdkws.OfflinePushInfo value) {
    value.getClass();
  if (offlinePushInfo_ != null &&
        offlinePushInfo_ != io.openim.android.sdk.protos.sdkws.OfflinePushInfo.getDefaultInstance()) {
      offlinePushInfo_ =
        io.openim.android.sdk.protos.sdkws.OfflinePushInfo.newBuilder(offlinePushInfo_).mergeFrom(value).buildPartial();
    } else {
      offlinePushInfo_ = value;
    }
    
  }
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   */
  private void clearOfflinePushInfo() {  offlinePushInfo_ = null;
    
  }

  public static final int ATUSERIDLIST_FIELD_NUMBER = 21;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> atUserIDList_;
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @return A list containing the atUserIDList.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getAtUserIDListList() {
    return atUserIDList_;
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @return The count of atUserIDList.
   */
  @java.lang.Override
  public int getAtUserIDListCount() {
    return atUserIDList_.size();
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param index The index of the element to return.
   * @return The atUserIDList at the given index.
   */
  @java.lang.Override
  public java.lang.String getAtUserIDList(int index) {
    return atUserIDList_.get(index);
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param index The index of the value to return.
   * @return The bytes of the atUserIDList at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAtUserIDListBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        atUserIDList_.get(index));
  }
  private void ensureAtUserIDListIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        atUserIDList_;  if (!tmp.isModifiable()) {
      atUserIDList_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param index The index to set the value at.
   * @param value The atUserIDList to set.
   */
  private void setAtUserIDList(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureAtUserIDListIsMutable();
    atUserIDList_.set(index, value);
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param value The atUserIDList to add.
   */
  private void addAtUserIDList(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureAtUserIDListIsMutable();
    atUserIDList_.add(value);
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param values The atUserIDList to add.
   */
  private void addAllAtUserIDList(
      java.lang.Iterable<java.lang.String> values) {
    ensureAtUserIDListIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, atUserIDList_);
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   */
  private void clearAtUserIDList() {
    atUserIDList_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param value The bytes of the atUserIDList to add.
   */
  private void addAtUserIDListBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureAtUserIDListIsMutable();
    atUserIDList_.add(value.toStringUtf8());
  }

  public static final int ATTACHEDINFO_FIELD_NUMBER = 22;
  private java.lang.String attachedInfo_;
  /**
   * <code>string attachedInfo = 22;</code>
   * @return The attachedInfo.
   */
  @java.lang.Override
  public java.lang.String getAttachedInfo() {
    return attachedInfo_;
  }
  /**
   * <code>string attachedInfo = 22;</code>
   * @return The bytes for attachedInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAttachedInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(attachedInfo_);
  }
  /**
   * <code>string attachedInfo = 22;</code>
   * @param value The attachedInfo to set.
   */
  private void setAttachedInfo(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    attachedInfo_ = value;
  }
  /**
   * <code>string attachedInfo = 22;</code>
   */
  private void clearAttachedInfo() {
    
    attachedInfo_ = getDefaultInstance().getAttachedInfo();
  }
  /**
   * <code>string attachedInfo = 22;</code>
   * @param value The bytes for attachedInfo to set.
   */
  private void setAttachedInfoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    attachedInfo_ = value.toStringUtf8();
    
  }

  public static final int EX_FIELD_NUMBER = 23;
  private java.lang.String ex_;
  /**
   * <code>string ex = 23;</code>
   * @return The ex.
   */
  @java.lang.Override
  public java.lang.String getEx() {
    return ex_;
  }
  /**
   * <code>string ex = 23;</code>
   * @return The bytes for ex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ex_);
  }
  /**
   * <code>string ex = 23;</code>
   * @param value The ex to set.
   */
  private void setEx(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ex_ = value;
  }
  /**
   * <code>string ex = 23;</code>
   */
  private void clearEx() {
    
    ex_ = getDefaultInstance().getEx();
  }
  /**
   * <code>string ex = 23;</code>
   * @param value The bytes for ex to set.
   */
  private void setExBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ex_ = value.toStringUtf8();
    
  }

  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.MsgData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.MsgData prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.MsgData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.MsgData, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.MsgData)
      io.openim.android.sdk.protos.sdkws.MsgDataOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.MsgData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string sendID = 1;</code>
     * @return The sendID.
     */
    @java.lang.Override
    public java.lang.String getSendID() {
      return instance.getSendID();
    }
    /**
     * <code>string sendID = 1;</code>
     * @return The bytes for sendID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSendIDBytes() {
      return instance.getSendIDBytes();
    }
    /**
     * <code>string sendID = 1;</code>
     * @param value The sendID to set.
     * @return This builder for chaining.
     */
    public Builder setSendID(
        java.lang.String value) {
      copyOnWrite();
      instance.setSendID(value);
      return this;
    }
    /**
     * <code>string sendID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendID() {
      copyOnWrite();
      instance.clearSendID();
      return this;
    }
    /**
     * <code>string sendID = 1;</code>
     * @param value The bytes for sendID to set.
     * @return This builder for chaining.
     */
    public Builder setSendIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSendIDBytes(value);
      return this;
    }

    /**
     * <code>string recvID = 2;</code>
     * @return The recvID.
     */
    @java.lang.Override
    public java.lang.String getRecvID() {
      return instance.getRecvID();
    }
    /**
     * <code>string recvID = 2;</code>
     * @return The bytes for recvID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecvIDBytes() {
      return instance.getRecvIDBytes();
    }
    /**
     * <code>string recvID = 2;</code>
     * @param value The recvID to set.
     * @return This builder for chaining.
     */
    public Builder setRecvID(
        java.lang.String value) {
      copyOnWrite();
      instance.setRecvID(value);
      return this;
    }
    /**
     * <code>string recvID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecvID() {
      copyOnWrite();
      instance.clearRecvID();
      return this;
    }
    /**
     * <code>string recvID = 2;</code>
     * @param value The bytes for recvID to set.
     * @return This builder for chaining.
     */
    public Builder setRecvIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRecvIDBytes(value);
      return this;
    }

    /**
     * <code>string groupID = 3;</code>
     * @return The groupID.
     */
    @java.lang.Override
    public java.lang.String getGroupID() {
      return instance.getGroupID();
    }
    /**
     * <code>string groupID = 3;</code>
     * @return The bytes for groupID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIDBytes() {
      return instance.getGroupIDBytes();
    }
    /**
     * <code>string groupID = 3;</code>
     * @param value The groupID to set.
     * @return This builder for chaining.
     */
    public Builder setGroupID(
        java.lang.String value) {
      copyOnWrite();
      instance.setGroupID(value);
      return this;
    }
    /**
     * <code>string groupID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupID() {
      copyOnWrite();
      instance.clearGroupID();
      return this;
    }
    /**
     * <code>string groupID = 3;</code>
     * @param value The bytes for groupID to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGroupIDBytes(value);
      return this;
    }

    /**
     * <code>string clientMsgID = 4;</code>
     * @return The clientMsgID.
     */
    @java.lang.Override
    public java.lang.String getClientMsgID() {
      return instance.getClientMsgID();
    }
    /**
     * <code>string clientMsgID = 4;</code>
     * @return The bytes for clientMsgID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientMsgIDBytes() {
      return instance.getClientMsgIDBytes();
    }
    /**
     * <code>string clientMsgID = 4;</code>
     * @param value The clientMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setClientMsgID(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientMsgID(value);
      return this;
    }
    /**
     * <code>string clientMsgID = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientMsgID() {
      copyOnWrite();
      instance.clearClientMsgID();
      return this;
    }
    /**
     * <code>string clientMsgID = 4;</code>
     * @param value The bytes for clientMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setClientMsgIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientMsgIDBytes(value);
      return this;
    }

    /**
     * <code>string serverMsgID = 5;</code>
     * @return The serverMsgID.
     */
    @java.lang.Override
    public java.lang.String getServerMsgID() {
      return instance.getServerMsgID();
    }
    /**
     * <code>string serverMsgID = 5;</code>
     * @return The bytes for serverMsgID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerMsgIDBytes() {
      return instance.getServerMsgIDBytes();
    }
    /**
     * <code>string serverMsgID = 5;</code>
     * @param value The serverMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setServerMsgID(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerMsgID(value);
      return this;
    }
    /**
     * <code>string serverMsgID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerMsgID() {
      copyOnWrite();
      instance.clearServerMsgID();
      return this;
    }
    /**
     * <code>string serverMsgID = 5;</code>
     * @param value The bytes for serverMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setServerMsgIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerMsgIDBytes(value);
      return this;
    }

    /**
     * <code>int32 senderPlatformID = 6;</code>
     * @return The senderPlatformID.
     */
    @java.lang.Override
    public int getSenderPlatformID() {
      return instance.getSenderPlatformID();
    }
    /**
     * <code>int32 senderPlatformID = 6;</code>
     * @param value The senderPlatformID to set.
     * @return This builder for chaining.
     */
    public Builder setSenderPlatformID(int value) {
      copyOnWrite();
      instance.setSenderPlatformID(value);
      return this;
    }
    /**
     * <code>int32 senderPlatformID = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderPlatformID() {
      copyOnWrite();
      instance.clearSenderPlatformID();
      return this;
    }

    /**
     * <code>string senderNickname = 7;</code>
     * @return The senderNickname.
     */
    @java.lang.Override
    public java.lang.String getSenderNickname() {
      return instance.getSenderNickname();
    }
    /**
     * <code>string senderNickname = 7;</code>
     * @return The bytes for senderNickname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNicknameBytes() {
      return instance.getSenderNicknameBytes();
    }
    /**
     * <code>string senderNickname = 7;</code>
     * @param value The senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNickname(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderNickname(value);
      return this;
    }
    /**
     * <code>string senderNickname = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderNickname() {
      copyOnWrite();
      instance.clearSenderNickname();
      return this;
    }
    /**
     * <code>string senderNickname = 7;</code>
     * @param value The bytes for senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNicknameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderNicknameBytes(value);
      return this;
    }

    /**
     * <code>string senderFaceURL = 8;</code>
     * @return The senderFaceURL.
     */
    @java.lang.Override
    public java.lang.String getSenderFaceURL() {
      return instance.getSenderFaceURL();
    }
    /**
     * <code>string senderFaceURL = 8;</code>
     * @return The bytes for senderFaceURL.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderFaceURLBytes() {
      return instance.getSenderFaceURLBytes();
    }
    /**
     * <code>string senderFaceURL = 8;</code>
     * @param value The senderFaceURL to set.
     * @return This builder for chaining.
     */
    public Builder setSenderFaceURL(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderFaceURL(value);
      return this;
    }
    /**
     * <code>string senderFaceURL = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderFaceURL() {
      copyOnWrite();
      instance.clearSenderFaceURL();
      return this;
    }
    /**
     * <code>string senderFaceURL = 8;</code>
     * @param value The bytes for senderFaceURL to set.
     * @return This builder for chaining.
     */
    public Builder setSenderFaceURLBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderFaceURLBytes(value);
      return this;
    }

    /**
     * <code>int32 sessionType = 9;</code>
     * @return The sessionType.
     */
    @java.lang.Override
    public int getSessionType() {
      return instance.getSessionType();
    }
    /**
     * <code>int32 sessionType = 9;</code>
     * @param value The sessionType to set.
     * @return This builder for chaining.
     */
    public Builder setSessionType(int value) {
      copyOnWrite();
      instance.setSessionType(value);
      return this;
    }
    /**
     * <code>int32 sessionType = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionType() {
      copyOnWrite();
      instance.clearSessionType();
      return this;
    }

    /**
     * <code>int32 msgFrom = 10;</code>
     * @return The msgFrom.
     */
    @java.lang.Override
    public int getMsgFrom() {
      return instance.getMsgFrom();
    }
    /**
     * <code>int32 msgFrom = 10;</code>
     * @param value The msgFrom to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFrom(int value) {
      copyOnWrite();
      instance.setMsgFrom(value);
      return this;
    }
    /**
     * <code>int32 msgFrom = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgFrom() {
      copyOnWrite();
      instance.clearMsgFrom();
      return this;
    }

    /**
     * <code>int32 contentType = 11;</code>
     * @return The contentType.
     */
    @java.lang.Override
    public int getContentType() {
      return instance.getContentType();
    }
    /**
     * <code>int32 contentType = 11;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(int value) {
      copyOnWrite();
      instance.setContentType(value);
      return this;
    }
    /**
     * <code>int32 contentType = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      copyOnWrite();
      instance.clearContentType();
      return this;
    }

    /**
     * <code>bytes content = 12;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return instance.getContent();
    }
    /**
     * <code>bytes content = 12;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContent(value);
      return this;
    }
    /**
     * <code>bytes content = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      copyOnWrite();
      instance.clearContent();
      return this;
    }

    /**
     * <code>int64 seq = 14;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return instance.getSeq();
    }
    /**
     * <code>int64 seq = 14;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(long value) {
      copyOnWrite();
      instance.setSeq(value);
      return this;
    }
    /**
     * <code>int64 seq = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      copyOnWrite();
      instance.clearSeq();
      return this;
    }

    /**
     * <code>int64 sendTime = 15;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return instance.getSendTime();
    }
    /**
     * <code>int64 sendTime = 15;</code>
     * @param value The sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTime(long value) {
      copyOnWrite();
      instance.setSendTime(value);
      return this;
    }
    /**
     * <code>int64 sendTime = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendTime() {
      copyOnWrite();
      instance.clearSendTime();
      return this;
    }

    /**
     * <code>int64 createTime = 16;</code>
     * @return The createTime.
     */
    @java.lang.Override
    public long getCreateTime() {
      return instance.getCreateTime();
    }
    /**
     * <code>int64 createTime = 16;</code>
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {
      copyOnWrite();
      instance.setCreateTime(value);
      return this;
    }
    /**
     * <code>int64 createTime = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      copyOnWrite();
      instance.clearCreateTime();
      return this;
    }

    /**
     * <code>int32 status = 17;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>int32 status = 17;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>int32 status = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>bool isRead = 18;</code>
     * @return The isRead.
     */
    @java.lang.Override
    public boolean getIsRead() {
      return instance.getIsRead();
    }
    /**
     * <code>bool isRead = 18;</code>
     * @param value The isRead to set.
     * @return This builder for chaining.
     */
    public Builder setIsRead(boolean value) {
      copyOnWrite();
      instance.setIsRead(value);
      return this;
    }
    /**
     * <code>bool isRead = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRead() {
      copyOnWrite();
      instance.clearIsRead();
      return this;
    }

    @java.lang.Override

    public int getOptionsCount() {
      return instance.getOptionsMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    @java.lang.Override

    public boolean containsOptions(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getOptionsMap().containsKey(key);
    }

    public Builder clearOptions() {
      copyOnWrite();
      instance.getMutableOptionsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */

    public Builder removeOptions(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableOptionsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getOptionsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getOptions() {
      return getOptionsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Boolean> getOptionsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getOptionsMap());
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    @java.lang.Override

    public boolean getOptionsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          instance.getOptionsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    @java.lang.Override

    public boolean getOptionsOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          instance.getOptionsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    public Builder putOptions(
        java.lang.String key,
        boolean value) {
      java.lang.Class<?> keyClass = key.getClass();
      
      copyOnWrite();
      instance.getMutableOptionsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; options = 19;</code>
     */
    public Builder putAllOptions(
        java.util.Map<java.lang.String, java.lang.Boolean> values) {
      copyOnWrite();
      instance.getMutableOptionsMap().putAll(values);
      return this;
    }

    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    @java.lang.Override
    public boolean hasOfflinePushInfo() {
      return instance.hasOfflinePushInfo();
    }
    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    @java.lang.Override
    public io.openim.android.sdk.protos.sdkws.OfflinePushInfo getOfflinePushInfo() {
      return instance.getOfflinePushInfo();
    }
    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    public Builder setOfflinePushInfo(io.openim.android.sdk.protos.sdkws.OfflinePushInfo value) {
      copyOnWrite();
      instance.setOfflinePushInfo(value);
      return this;
      }
    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    public Builder setOfflinePushInfo(
        io.openim.android.sdk.protos.sdkws.OfflinePushInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setOfflinePushInfo(builderForValue.build());
      return this;
    }
    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    public Builder mergeOfflinePushInfo(io.openim.android.sdk.protos.sdkws.OfflinePushInfo value) {
      copyOnWrite();
      instance.mergeOfflinePushInfo(value);
      return this;
    }
    /**
     * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
     */
    public Builder clearOfflinePushInfo() {  copyOnWrite();
      instance.clearOfflinePushInfo();
      return this;
    }

    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @return A list containing the atUserIDList.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getAtUserIDListList() {
      return java.util.Collections.unmodifiableList(
          instance.getAtUserIDListList());
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @return The count of atUserIDList.
     */
    @java.lang.Override
    public int getAtUserIDListCount() {
      return instance.getAtUserIDListCount();
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param index The index of the element to return.
     * @return The atUserIDList at the given index.
     */
    @java.lang.Override
    public java.lang.String getAtUserIDList(int index) {
      return instance.getAtUserIDList(index);
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param index The index of the value to return.
     * @return The bytes of the atUserIDList at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAtUserIDListBytes(int index) {
      return instance.getAtUserIDListBytes(index);
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param index The index to set the value at.
     * @param value The atUserIDList to set.
     * @return This builder for chaining.
     */
    public Builder setAtUserIDList(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setAtUserIDList(index, value);
      return this;
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param value The atUserIDList to add.
     * @return This builder for chaining.
     */
    public Builder addAtUserIDList(
        java.lang.String value) {
      copyOnWrite();
      instance.addAtUserIDList(value);
      return this;
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param values The atUserIDList to add.
     * @return This builder for chaining.
     */
    public Builder addAllAtUserIDList(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllAtUserIDList(values);
      return this;
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearAtUserIDList() {
      copyOnWrite();
      instance.clearAtUserIDList();
      return this;
    }
    /**
     * <code>repeated string atUserIDList = 21;</code>
     * @param value The bytes of the atUserIDList to add.
     * @return This builder for chaining.
     */
    public Builder addAtUserIDListBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addAtUserIDListBytes(value);
      return this;
    }

    /**
     * <code>string attachedInfo = 22;</code>
     * @return The attachedInfo.
     */
    @java.lang.Override
    public java.lang.String getAttachedInfo() {
      return instance.getAttachedInfo();
    }
    /**
     * <code>string attachedInfo = 22;</code>
     * @return The bytes for attachedInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAttachedInfoBytes() {
      return instance.getAttachedInfoBytes();
    }
    /**
     * <code>string attachedInfo = 22;</code>
     * @param value The attachedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAttachedInfo(
        java.lang.String value) {
      copyOnWrite();
      instance.setAttachedInfo(value);
      return this;
    }
    /**
     * <code>string attachedInfo = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttachedInfo() {
      copyOnWrite();
      instance.clearAttachedInfo();
      return this;
    }
    /**
     * <code>string attachedInfo = 22;</code>
     * @param value The bytes for attachedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAttachedInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAttachedInfoBytes(value);
      return this;
    }

    /**
     * <code>string ex = 23;</code>
     * @return The ex.
     */
    @java.lang.Override
    public java.lang.String getEx() {
      return instance.getEx();
    }
    /**
     * <code>string ex = 23;</code>
     * @return The bytes for ex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExBytes() {
      return instance.getExBytes();
    }
    /**
     * <code>string ex = 23;</code>
     * @param value The ex to set.
     * @return This builder for chaining.
     */
    public Builder setEx(
        java.lang.String value) {
      copyOnWrite();
      instance.setEx(value);
      return this;
    }
    /**
     * <code>string ex = 23;</code>
     * @return This builder for chaining.
     */
    public Builder clearEx() {
      copyOnWrite();
      instance.clearEx();
      return this;
    }
    /**
     * <code>string ex = 23;</code>
     * @param value The bytes for ex to set.
     * @return This builder for chaining.
     */
    public Builder setExBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.MsgData)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.MsgData();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "sendID_",
            "recvID_",
            "groupID_",
            "clientMsgID_",
            "serverMsgID_",
            "senderPlatformID_",
            "senderNickname_",
            "senderFaceURL_",
            "sessionType_",
            "msgFrom_",
            "contentType_",
            "content_",
            "seq_",
            "sendTime_",
            "createTime_",
            "status_",
            "isRead_",
            "options_",
            OptionsDefaultEntryHolder.defaultEntry,
            "offlinePushInfo_",
            "atUserIDList_",
            "attachedInfo_",
            "ex_",
          };
          java.lang.String info =
              "\u0000\u0016\u0000\u0000\u0001\u0017\u0016\u0001\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0004\u0007\u0208\b\u0208\t\u0004\n\u0004" +
              "\u000b\u0004\f\n\u000e\u0002\u000f\u0002\u0010\u0002\u0011\u0004\u0012\u0007\u0013" +
              "2\u0014\t\u0015\u021a\u0016\u0208\u0017\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.MsgData> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.MsgData.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.MsgData>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.MsgData)
  private static final io.openim.android.sdk.protos.sdkws.MsgData DEFAULT_INSTANCE;
  static {
    MsgData defaultInstance = new MsgData();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      MsgData.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.MsgData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MsgData> PARSER;

  public static com.google.protobuf.Parser<MsgData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

