// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface MsgDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.MsgData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string sendID = 1;</code>
   * @return The sendID.
   */
  java.lang.String getSendID();
  /**
   * <code>string sendID = 1;</code>
   * @return The bytes for sendID.
   */
  com.google.protobuf.ByteString
      getSendIDBytes();

  /**
   * <code>string recvID = 2;</code>
   * @return The recvID.
   */
  java.lang.String getRecvID();
  /**
   * <code>string recvID = 2;</code>
   * @return The bytes for recvID.
   */
  com.google.protobuf.ByteString
      getRecvIDBytes();

  /**
   * <code>string groupID = 3;</code>
   * @return The groupID.
   */
  java.lang.String getGroupID();
  /**
   * <code>string groupID = 3;</code>
   * @return The bytes for groupID.
   */
  com.google.protobuf.ByteString
      getGroupIDBytes();

  /**
   * <code>string clientMsgID = 4;</code>
   * @return The clientMsgID.
   */
  java.lang.String getClientMsgID();
  /**
   * <code>string clientMsgID = 4;</code>
   * @return The bytes for clientMsgID.
   */
  com.google.protobuf.ByteString
      getClientMsgIDBytes();

  /**
   * <code>string serverMsgID = 5;</code>
   * @return The serverMsgID.
   */
  java.lang.String getServerMsgID();
  /**
   * <code>string serverMsgID = 5;</code>
   * @return The bytes for serverMsgID.
   */
  com.google.protobuf.ByteString
      getServerMsgIDBytes();

  /**
   * <code>int32 senderPlatformID = 6;</code>
   * @return The senderPlatformID.
   */
  int getSenderPlatformID();

  /**
   * <code>string senderNickname = 7;</code>
   * @return The senderNickname.
   */
  java.lang.String getSenderNickname();
  /**
   * <code>string senderNickname = 7;</code>
   * @return The bytes for senderNickname.
   */
  com.google.protobuf.ByteString
      getSenderNicknameBytes();

  /**
   * <code>string senderFaceURL = 8;</code>
   * @return The senderFaceURL.
   */
  java.lang.String getSenderFaceURL();
  /**
   * <code>string senderFaceURL = 8;</code>
   * @return The bytes for senderFaceURL.
   */
  com.google.protobuf.ByteString
      getSenderFaceURLBytes();

  /**
   * <code>int32 sessionType = 9;</code>
   * @return The sessionType.
   */
  int getSessionType();

  /**
   * <code>int32 msgFrom = 10;</code>
   * @return The msgFrom.
   */
  int getMsgFrom();

  /**
   * <code>int32 contentType = 11;</code>
   * @return The contentType.
   */
  int getContentType();

  /**
   * <code>bytes content = 12;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int64 seq = 14;</code>
   * @return The seq.
   */
  long getSeq();

  /**
   * <code>int64 sendTime = 15;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>int64 createTime = 16;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>int32 status = 17;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>bool isRead = 18;</code>
   * @return The isRead.
   */
  boolean getIsRead();

  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  int getOptionsCount();
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  boolean containsOptions(
      java.lang.String key);
  /**
   * Use {@link #getOptionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getOptions();
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getOptionsMap();
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */

  boolean getOptionsOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <code>map&lt;string, bool&gt; options = 19;</code>
   */

  boolean getOptionsOrThrow(
      java.lang.String key);

  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   * @return Whether the offlinePushInfo field is set.
   */
  boolean hasOfflinePushInfo();
  /**
   * <code>.openim.sdkws.OfflinePushInfo offlinePushInfo = 20;</code>
   * @return The offlinePushInfo.
   */
  io.openim.android.sdk.protos.sdkws.OfflinePushInfo getOfflinePushInfo();

  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @return A list containing the atUserIDList.
   */
  java.util.List<java.lang.String>
      getAtUserIDListList();
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @return The count of atUserIDList.
   */
  int getAtUserIDListCount();
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param index The index of the element to return.
   * @return The atUserIDList at the given index.
   */
  java.lang.String getAtUserIDList(int index);
  /**
   * <code>repeated string atUserIDList = 21;</code>
   * @param index The index of the element to return.
   * @return The atUserIDList at the given index.
   */
  com.google.protobuf.ByteString
      getAtUserIDListBytes(int index);

  /**
   * <code>string attachedInfo = 22;</code>
   * @return The attachedInfo.
   */
  java.lang.String getAttachedInfo();
  /**
   * <code>string attachedInfo = 22;</code>
   * @return The bytes for attachedInfo.
   */
  com.google.protobuf.ByteString
      getAttachedInfoBytes();

  /**
   * <code>string ex = 23;</code>
   * @return The ex.
   */
  java.lang.String getEx();
  /**
   * <code>string ex = 23;</code>
   * @return The bytes for ex.
   */
  com.google.protobuf.ByteString
      getExBytes();
}
