// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.OfflinePushInfo}
 */
public  final class OfflinePushInfo extends
    com.google.protobuf.GeneratedMessageLite<
        OfflinePushInfo, OfflinePushInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.OfflinePushInfo)
    OfflinePushInfoOrBuilder {
  private OfflinePushInfo() {
    title_ = "";
    desc_ = "";
    ex_ = "";
    iOSPushSound_ = "";
    signalInfo_ = "";
  }
  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 1;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <code>string title = 1;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 1;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int DESC_FIELD_NUMBER = 2;
  private java.lang.String desc_;
  /**
   * <code>string desc = 2;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    return desc_;
  }
  /**
   * <code>string desc = 2;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(desc_);
  }
  /**
   * <code>string desc = 2;</code>
   * @param value The desc to set.
   */
  private void setDesc(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    desc_ = value;
  }
  /**
   * <code>string desc = 2;</code>
   */
  private void clearDesc() {
    
    desc_ = getDefaultInstance().getDesc();
  }
  /**
   * <code>string desc = 2;</code>
   * @param value The bytes for desc to set.
   */
  private void setDescBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    desc_ = value.toStringUtf8();
    
  }

  public static final int EX_FIELD_NUMBER = 3;
  private java.lang.String ex_;
  /**
   * <code>string ex = 3;</code>
   * @return The ex.
   */
  @java.lang.Override
  public java.lang.String getEx() {
    return ex_;
  }
  /**
   * <code>string ex = 3;</code>
   * @return The bytes for ex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ex_);
  }
  /**
   * <code>string ex = 3;</code>
   * @param value The ex to set.
   */
  private void setEx(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    ex_ = value;
  }
  /**
   * <code>string ex = 3;</code>
   */
  private void clearEx() {
    
    ex_ = getDefaultInstance().getEx();
  }
  /**
   * <code>string ex = 3;</code>
   * @param value The bytes for ex to set.
   */
  private void setExBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ex_ = value.toStringUtf8();
    
  }

  public static final int IOSPUSHSOUND_FIELD_NUMBER = 4;
  private java.lang.String iOSPushSound_;
  /**
   * <code>string iOSPushSound = 4;</code>
   * @return The iOSPushSound.
   */
  @java.lang.Override
  public java.lang.String getIOSPushSound() {
    return iOSPushSound_;
  }
  /**
   * <code>string iOSPushSound = 4;</code>
   * @return The bytes for iOSPushSound.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIOSPushSoundBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iOSPushSound_);
  }
  /**
   * <code>string iOSPushSound = 4;</code>
   * @param value The iOSPushSound to set.
   */
  private void setIOSPushSound(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    iOSPushSound_ = value;
  }
  /**
   * <code>string iOSPushSound = 4;</code>
   */
  private void clearIOSPushSound() {
    
    iOSPushSound_ = getDefaultInstance().getIOSPushSound();
  }
  /**
   * <code>string iOSPushSound = 4;</code>
   * @param value The bytes for iOSPushSound to set.
   */
  private void setIOSPushSoundBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    iOSPushSound_ = value.toStringUtf8();
    
  }

  public static final int IOSBADGECOUNT_FIELD_NUMBER = 5;
  private boolean iOSBadgeCount_;
  /**
   * <code>bool iOSBadgeCount = 5;</code>
   * @return The iOSBadgeCount.
   */
  @java.lang.Override
  public boolean getIOSBadgeCount() {
    return iOSBadgeCount_;
  }
  /**
   * <code>bool iOSBadgeCount = 5;</code>
   * @param value The iOSBadgeCount to set.
   */
  private void setIOSBadgeCount(boolean value) {
    
    iOSBadgeCount_ = value;
  }
  /**
   * <code>bool iOSBadgeCount = 5;</code>
   */
  private void clearIOSBadgeCount() {
    
    iOSBadgeCount_ = false;
  }

  public static final int SIGNALINFO_FIELD_NUMBER = 6;
  private java.lang.String signalInfo_;
  /**
   * <code>string signalInfo = 6;</code>
   * @return The signalInfo.
   */
  @java.lang.Override
  public java.lang.String getSignalInfo() {
    return signalInfo_;
  }
  /**
   * <code>string signalInfo = 6;</code>
   * @return The bytes for signalInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignalInfoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(signalInfo_);
  }
  /**
   * <code>string signalInfo = 6;</code>
   * @param value The signalInfo to set.
   */
  private void setSignalInfo(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    signalInfo_ = value;
  }
  /**
   * <code>string signalInfo = 6;</code>
   */
  private void clearSignalInfo() {
    
    signalInfo_ = getDefaultInstance().getSignalInfo();
  }
  /**
   * <code>string signalInfo = 6;</code>
   * @param value The bytes for signalInfo to set.
   */
  private void setSignalInfoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    signalInfo_ = value.toStringUtf8();
    
  }

  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.OfflinePushInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.OfflinePushInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.OfflinePushInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.OfflinePushInfo)
      io.openim.android.sdk.protos.sdkws.OfflinePushInfoOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.OfflinePushInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>string desc = 2;</code>
     * @return The desc.
     */
    @java.lang.Override
    public java.lang.String getDesc() {
      return instance.getDesc();
    }
    /**
     * <code>string desc = 2;</code>
     * @return The bytes for desc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescBytes() {
      return instance.getDescBytes();
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      copyOnWrite();
      instance.setDesc(value);
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      copyOnWrite();
      instance.clearDesc();
      return this;
    }
    /**
     * <code>string desc = 2;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescBytes(value);
      return this;
    }

    /**
     * <code>string ex = 3;</code>
     * @return The ex.
     */
    @java.lang.Override
    public java.lang.String getEx() {
      return instance.getEx();
    }
    /**
     * <code>string ex = 3;</code>
     * @return The bytes for ex.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExBytes() {
      return instance.getExBytes();
    }
    /**
     * <code>string ex = 3;</code>
     * @param value The ex to set.
     * @return This builder for chaining.
     */
    public Builder setEx(
        java.lang.String value) {
      copyOnWrite();
      instance.setEx(value);
      return this;
    }
    /**
     * <code>string ex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEx() {
      copyOnWrite();
      instance.clearEx();
      return this;
    }
    /**
     * <code>string ex = 3;</code>
     * @param value The bytes for ex to set.
     * @return This builder for chaining.
     */
    public Builder setExBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExBytes(value);
      return this;
    }

    /**
     * <code>string iOSPushSound = 4;</code>
     * @return The iOSPushSound.
     */
    @java.lang.Override
    public java.lang.String getIOSPushSound() {
      return instance.getIOSPushSound();
    }
    /**
     * <code>string iOSPushSound = 4;</code>
     * @return The bytes for iOSPushSound.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIOSPushSoundBytes() {
      return instance.getIOSPushSoundBytes();
    }
    /**
     * <code>string iOSPushSound = 4;</code>
     * @param value The iOSPushSound to set.
     * @return This builder for chaining.
     */
    public Builder setIOSPushSound(
        java.lang.String value) {
      copyOnWrite();
      instance.setIOSPushSound(value);
      return this;
    }
    /**
     * <code>string iOSPushSound = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIOSPushSound() {
      copyOnWrite();
      instance.clearIOSPushSound();
      return this;
    }
    /**
     * <code>string iOSPushSound = 4;</code>
     * @param value The bytes for iOSPushSound to set.
     * @return This builder for chaining.
     */
    public Builder setIOSPushSoundBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIOSPushSoundBytes(value);
      return this;
    }

    /**
     * <code>bool iOSBadgeCount = 5;</code>
     * @return The iOSBadgeCount.
     */
    @java.lang.Override
    public boolean getIOSBadgeCount() {
      return instance.getIOSBadgeCount();
    }
    /**
     * <code>bool iOSBadgeCount = 5;</code>
     * @param value The iOSBadgeCount to set.
     * @return This builder for chaining.
     */
    public Builder setIOSBadgeCount(boolean value) {
      copyOnWrite();
      instance.setIOSBadgeCount(value);
      return this;
    }
    /**
     * <code>bool iOSBadgeCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIOSBadgeCount() {
      copyOnWrite();
      instance.clearIOSBadgeCount();
      return this;
    }

    /**
     * <code>string signalInfo = 6;</code>
     * @return The signalInfo.
     */
    @java.lang.Override
    public java.lang.String getSignalInfo() {
      return instance.getSignalInfo();
    }
    /**
     * <code>string signalInfo = 6;</code>
     * @return The bytes for signalInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignalInfoBytes() {
      return instance.getSignalInfoBytes();
    }
    /**
     * <code>string signalInfo = 6;</code>
     * @param value The signalInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSignalInfo(
        java.lang.String value) {
      copyOnWrite();
      instance.setSignalInfo(value);
      return this;
    }
    /**
     * <code>string signalInfo = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignalInfo() {
      copyOnWrite();
      instance.clearSignalInfo();
      return this;
    }
    /**
     * <code>string signalInfo = 6;</code>
     * @param value The bytes for signalInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSignalInfoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSignalInfoBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.OfflinePushInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.OfflinePushInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "title_",
            "desc_",
            "ex_",
            "iOSPushSound_",
            "iOSBadgeCount_",
            "signalInfo_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0007\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.OfflinePushInfo> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.OfflinePushInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.OfflinePushInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.OfflinePushInfo)
  private static final io.openim.android.sdk.protos.sdkws.OfflinePushInfo DEFAULT_INSTANCE;
  static {
    OfflinePushInfo defaultInstance = new OfflinePushInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OfflinePushInfo.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.OfflinePushInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OfflinePushInfo> PARSER;

  public static com.google.protobuf.Parser<OfflinePushInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

