// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf enum {@code openim.sdkws.PullOrder}
 */
public enum PullOrder
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PullOrderAsc = 0;</code>
   */
  PullOrderAsc(0),
  /**
   * <code>PullOrderDesc = 1;</code>
   */
  PullOrderDesc(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PullOrderAsc = 0;</code>
   */
  public static final int PullOrderAsc_VALUE = 0;
  /**
   * <code>PullOrderDesc = 1;</code>
   */
  public static final int PullOrderDesc_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PullOrder valueOf(int value) {
    return forNumber(value);
  }

  public static PullOrder forNumber(int value) {
    switch (value) {
      case 0: return PullOrderAsc;
      case 1: return PullOrderDesc;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PullOrder>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PullOrder> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PullOrder>() {
          @java.lang.Override
          public PullOrder findValueByNumber(int number) {
            return PullOrder.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PullOrderVerifier.INSTANCE;
  }

  private static final class PullOrderVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PullOrderVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return PullOrder.forNumber(number) != null;
          }
        };

  private final int value;

  private PullOrder(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:openim.sdkws.PullOrder)
}

