// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.PullMsgs}
 */
public  final class PullMsgs extends
    com.google.protobuf.GeneratedMessageLite<
        PullMsgs, PullMsgs.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.PullMsgs)
    PullMsgsOrBuilder {
  private PullMsgs() {
    msgs_ = emptyProtobufList();
  }
  public static final int MSGS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<io.openim.android.sdk.protos.sdkws.MsgData> msgs_;
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.openim.android.sdk.protos.sdkws.MsgData> getMsgsList() {
    return msgs_;
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  public java.util.List<? extends io.openim.android.sdk.protos.sdkws.MsgDataOrBuilder> 
      getMsgsOrBuilderList() {
    return msgs_;
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  @java.lang.Override
  public int getMsgsCount() {
    return msgs_.size();
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  @java.lang.Override
  public io.openim.android.sdk.protos.sdkws.MsgData getMsgs(int index) {
    return msgs_.get(index);
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  public io.openim.android.sdk.protos.sdkws.MsgDataOrBuilder getMsgsOrBuilder(
      int index) {
    return msgs_.get(index);
  }
  private void ensureMsgsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.openim.android.sdk.protos.sdkws.MsgData> tmp = msgs_;
    if (!tmp.isModifiable()) {
      msgs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void setMsgs(
      int index, io.openim.android.sdk.protos.sdkws.MsgData value) {
    value.getClass();
  ensureMsgsIsMutable();
    msgs_.set(index, value);
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void addMsgs(io.openim.android.sdk.protos.sdkws.MsgData value) {
    value.getClass();
  ensureMsgsIsMutable();
    msgs_.add(value);
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void addMsgs(
      int index, io.openim.android.sdk.protos.sdkws.MsgData value) {
    value.getClass();
  ensureMsgsIsMutable();
    msgs_.add(index, value);
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void addAllMsgs(
      java.lang.Iterable<? extends io.openim.android.sdk.protos.sdkws.MsgData> values) {
    ensureMsgsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, msgs_);
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void clearMsgs() {
    msgs_ = emptyProtobufList();
  }
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  private void removeMsgs(int index) {
    ensureMsgsIsMutable();
    msgs_.remove(index);
  }

  public static final int ISEND_FIELD_NUMBER = 2;
  private boolean isEnd_;
  /**
   * <code>bool isEnd = 2;</code>
   * @return The isEnd.
   */
  @java.lang.Override
  public boolean getIsEnd() {
    return isEnd_;
  }
  /**
   * <code>bool isEnd = 2;</code>
   * @param value The isEnd to set.
   */
  private void setIsEnd(boolean value) {
    
    isEnd_ = value;
  }
  /**
   * <code>bool isEnd = 2;</code>
   */
  private void clearIsEnd() {
    
    isEnd_ = false;
  }

  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.PullMsgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.PullMsgs prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.PullMsgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.PullMsgs, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.PullMsgs)
      io.openim.android.sdk.protos.sdkws.PullMsgsOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.PullMsgs.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.openim.android.sdk.protos.sdkws.MsgData> getMsgsList() {
      return java.util.Collections.unmodifiableList(
          instance.getMsgsList());
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    @java.lang.Override
    public int getMsgsCount() {
      return instance.getMsgsCount();
    }/**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    @java.lang.Override
    public io.openim.android.sdk.protos.sdkws.MsgData getMsgs(int index) {
      return instance.getMsgs(index);
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder setMsgs(
        int index, io.openim.android.sdk.protos.sdkws.MsgData value) {
      copyOnWrite();
      instance.setMsgs(index, value);
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder setMsgs(
        int index, io.openim.android.sdk.protos.sdkws.MsgData.Builder builderForValue) {
      copyOnWrite();
      instance.setMsgs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder addMsgs(io.openim.android.sdk.protos.sdkws.MsgData value) {
      copyOnWrite();
      instance.addMsgs(value);
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder addMsgs(
        int index, io.openim.android.sdk.protos.sdkws.MsgData value) {
      copyOnWrite();
      instance.addMsgs(index, value);
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder addMsgs(
        io.openim.android.sdk.protos.sdkws.MsgData.Builder builderForValue) {
      copyOnWrite();
      instance.addMsgs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder addMsgs(
        int index, io.openim.android.sdk.protos.sdkws.MsgData.Builder builderForValue) {
      copyOnWrite();
      instance.addMsgs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder addAllMsgs(
        java.lang.Iterable<? extends io.openim.android.sdk.protos.sdkws.MsgData> values) {
      copyOnWrite();
      instance.addAllMsgs(values);
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder clearMsgs() {
      copyOnWrite();
      instance.clearMsgs();
      return this;
    }
    /**
     * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
     */
    public Builder removeMsgs(int index) {
      copyOnWrite();
      instance.removeMsgs(index);
      return this;
    }

    /**
     * <code>bool isEnd = 2;</code>
     * @return The isEnd.
     */
    @java.lang.Override
    public boolean getIsEnd() {
      return instance.getIsEnd();
    }
    /**
     * <code>bool isEnd = 2;</code>
     * @param value The isEnd to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnd(boolean value) {
      copyOnWrite();
      instance.setIsEnd(value);
      return this;
    }
    /**
     * <code>bool isEnd = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEnd() {
      copyOnWrite();
      instance.clearIsEnd();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.PullMsgs)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.PullMsgs();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "msgs_",
            io.openim.android.sdk.protos.sdkws.MsgData.class,
            "isEnd_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.PullMsgs> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.PullMsgs.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.PullMsgs>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.PullMsgs)
  private static final io.openim.android.sdk.protos.sdkws.PullMsgs DEFAULT_INSTANCE;
  static {
    PullMsgs defaultInstance = new PullMsgs();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PullMsgs.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.PullMsgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PullMsgs> PARSER;

  public static com.google.protobuf.Parser<PullMsgs> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

