// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface PullMessageBySeqsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.PullMessageBySeqsReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>repeated .openim.sdkws.SeqRange seqRanges = 2;</code>
   */
  java.util.List<io.openim.android.sdk.protos.sdkws.SeqRange> 
      getSeqRangesList();
  /**
   * <code>repeated .openim.sdkws.SeqRange seqRanges = 2;</code>
   */
  io.openim.android.sdk.protos.sdkws.SeqRange getSeqRanges(int index);
  /**
   * <code>repeated .openim.sdkws.SeqRange seqRanges = 2;</code>
   */
  int getSeqRangesCount();

  /**
   * <code>.openim.sdkws.PullOrder order = 3;</code>
   * @return The enum numeric value on the wire for order.
   */
  int getOrderValue();
  /**
   * <code>.openim.sdkws.PullOrder order = 3;</code>
   * @return The order.
   */
  io.openim.android.sdk.protos.sdkws.PullOrder getOrder();
}
