// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface PullMsgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.PullMsgs)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  java.util.List<io.openim.android.sdk.protos.sdkws.MsgData> 
      getMsgsList();
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  io.openim.android.sdk.protos.sdkws.MsgData getMsgs(int index);
  /**
   * <code>repeated .openim.sdkws.MsgData Msgs = 1;</code>
   */
  int getMsgsCount();

  /**
   * <code>bool isEnd = 2;</code>
   * @return The isEnd.
   */
  boolean getIsEnd();
}
