// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.SeqRange}
 */
public  final class SeqRange extends
    com.google.protobuf.GeneratedMessageLite<
        SeqRange, SeqRange.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.SeqRange)
    SeqRangeOrBuilder {
  private SeqRange() {
    conversationID_ = "";
  }
  public static final int CONVERSATIONID_FIELD_NUMBER = 1;
  private java.lang.String conversationID_;
  /**
   * <code>string conversationID = 1;</code>
   * @return The conversationID.
   */
  @java.lang.Override
  public java.lang.String getConversationID() {
    return conversationID_;
  }
  /**
   * <code>string conversationID = 1;</code>
   * @return The bytes for conversationID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conversationID_);
  }
  /**
   * <code>string conversationID = 1;</code>
   * @param value The conversationID to set.
   */
  private void setConversationID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    conversationID_ = value;
  }
  /**
   * <code>string conversationID = 1;</code>
   */
  private void clearConversationID() {
    
    conversationID_ = getDefaultInstance().getConversationID();
  }
  /**
   * <code>string conversationID = 1;</code>
   * @param value The bytes for conversationID to set.
   */
  private void setConversationIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conversationID_ = value.toStringUtf8();
    
  }

  public static final int BEGIN_FIELD_NUMBER = 2;
  private long begin_;
  /**
   * <code>int64 begin = 2;</code>
   * @return The begin.
   */
  @java.lang.Override
  public long getBegin() {
    return begin_;
  }
  /**
   * <code>int64 begin = 2;</code>
   * @param value The begin to set.
   */
  private void setBegin(long value) {
    
    begin_ = value;
  }
  /**
   * <code>int64 begin = 2;</code>
   */
  private void clearBegin() {
    
    begin_ = 0L;
  }

  public static final int END_FIELD_NUMBER = 3;
  private long end_;
  /**
   * <code>int64 end = 3;</code>
   * @return The end.
   */
  @java.lang.Override
  public long getEnd() {
    return end_;
  }
  /**
   * <code>int64 end = 3;</code>
   * @param value The end to set.
   */
  private void setEnd(long value) {
    
    end_ = value;
  }
  /**
   * <code>int64 end = 3;</code>
   */
  private void clearEnd() {
    
    end_ = 0L;
  }

  public static final int NUM_FIELD_NUMBER = 4;
  private long num_;
  /**
   * <code>int64 num = 4;</code>
   * @return The num.
   */
  @java.lang.Override
  public long getNum() {
    return num_;
  }
  /**
   * <code>int64 num = 4;</code>
   * @param value The num to set.
   */
  private void setNum(long value) {
    
    num_ = value;
  }
  /**
   * <code>int64 num = 4;</code>
   */
  private void clearNum() {
    
    num_ = 0L;
  }

  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.SeqRange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.SeqRange prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.SeqRange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.SeqRange, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.SeqRange)
      io.openim.android.sdk.protos.sdkws.SeqRangeOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.SeqRange.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string conversationID = 1;</code>
     * @return The conversationID.
     */
    @java.lang.Override
    public java.lang.String getConversationID() {
      return instance.getConversationID();
    }
    /**
     * <code>string conversationID = 1;</code>
     * @return The bytes for conversationID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIDBytes() {
      return instance.getConversationIDBytes();
    }
    /**
     * <code>string conversationID = 1;</code>
     * @param value The conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationID(
        java.lang.String value) {
      copyOnWrite();
      instance.setConversationID(value);
      return this;
    }
    /**
     * <code>string conversationID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationID() {
      copyOnWrite();
      instance.clearConversationID();
      return this;
    }
    /**
     * <code>string conversationID = 1;</code>
     * @param value The bytes for conversationID to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConversationIDBytes(value);
      return this;
    }

    /**
     * <code>int64 begin = 2;</code>
     * @return The begin.
     */
    @java.lang.Override
    public long getBegin() {
      return instance.getBegin();
    }
    /**
     * <code>int64 begin = 2;</code>
     * @param value The begin to set.
     * @return This builder for chaining.
     */
    public Builder setBegin(long value) {
      copyOnWrite();
      instance.setBegin(value);
      return this;
    }
    /**
     * <code>int64 begin = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBegin() {
      copyOnWrite();
      instance.clearBegin();
      return this;
    }

    /**
     * <code>int64 end = 3;</code>
     * @return The end.
     */
    @java.lang.Override
    public long getEnd() {
      return instance.getEnd();
    }
    /**
     * <code>int64 end = 3;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(long value) {
      copyOnWrite();
      instance.setEnd(value);
      return this;
    }
    /**
     * <code>int64 end = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      copyOnWrite();
      instance.clearEnd();
      return this;
    }

    /**
     * <code>int64 num = 4;</code>
     * @return The num.
     */
    @java.lang.Override
    public long getNum() {
      return instance.getNum();
    }
    /**
     * <code>int64 num = 4;</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(long value) {
      copyOnWrite();
      instance.setNum(value);
      return this;
    }
    /**
     * <code>int64 num = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      copyOnWrite();
      instance.clearNum();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.SeqRange)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.SeqRange();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "conversationID_",
            "begin_",
            "end_",
            "num_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
              "\u0003\u0002\u0004\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.SeqRange> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.SeqRange.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.SeqRange>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.SeqRange)
  private static final io.openim.android.sdk.protos.sdkws.SeqRange DEFAULT_INSTANCE;
  static {
    SeqRange defaultInstance = new SeqRange();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SeqRange.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.SeqRange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SeqRange> PARSER;

  public static com.google.protobuf.Parser<SeqRange> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

