// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

public interface SeqRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.sdkws.SeqRange)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string conversationID = 1;</code>
   * @return The conversationID.
   */
  java.lang.String getConversationID();
  /**
   * <code>string conversationID = 1;</code>
   * @return The bytes for conversationID.
   */
  com.google.protobuf.ByteString
      getConversationIDBytes();

  /**
   * <code>int64 begin = 2;</code>
   * @return The begin.
   */
  long getBegin();

  /**
   * <code>int64 end = 3;</code>
   * @return The end.
   */
  long getEnd();

  /**
   * <code>int64 num = 4;</code>
   * @return The num.
   */
  long getNum();
}
