// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/sdkws.proto

package io.openim.android.sdk.protos.sdkws;

/**
 * Protobuf type {@code openim.sdkws.UserSendMsgResp}
 */
public  final class UserSendMsgResp extends
    com.google.protobuf.GeneratedMessageLite<
        UserSendMsgResp, UserSendMsgResp.Builder> implements
    // @@protoc_insertion_point(message_implements:openim.sdkws.UserSendMsgResp)
    UserSendMsgRespOrBuilder {
  private UserSendMsgResp() {
    serverMsgID_ = "";
    clientMsgID_ = "";
  }
  public static final int SERVERMSGID_FIELD_NUMBER = 1;
  private java.lang.String serverMsgID_;
  /**
   * <code>string serverMsgID = 1;</code>
   * @return The serverMsgID.
   */
  @java.lang.Override
  public java.lang.String getServerMsgID() {
    return serverMsgID_;
  }
  /**
   * <code>string serverMsgID = 1;</code>
   * @return The bytes for serverMsgID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerMsgIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverMsgID_);
  }
  /**
   * <code>string serverMsgID = 1;</code>
   * @param value The serverMsgID to set.
   */
  private void setServerMsgID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    serverMsgID_ = value;
  }
  /**
   * <code>string serverMsgID = 1;</code>
   */
  private void clearServerMsgID() {
    
    serverMsgID_ = getDefaultInstance().getServerMsgID();
  }
  /**
   * <code>string serverMsgID = 1;</code>
   * @param value The bytes for serverMsgID to set.
   */
  private void setServerMsgIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    serverMsgID_ = value.toStringUtf8();
    
  }

  public static final int CLIENTMSGID_FIELD_NUMBER = 2;
  private java.lang.String clientMsgID_;
  /**
   * <code>string clientMsgID = 2;</code>
   * @return The clientMsgID.
   */
  @java.lang.Override
  public java.lang.String getClientMsgID() {
    return clientMsgID_;
  }
  /**
   * <code>string clientMsgID = 2;</code>
   * @return The bytes for clientMsgID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientMsgIDBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(clientMsgID_);
  }
  /**
   * <code>string clientMsgID = 2;</code>
   * @param value The clientMsgID to set.
   */
  private void setClientMsgID(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    clientMsgID_ = value;
  }
  /**
   * <code>string clientMsgID = 2;</code>
   */
  private void clearClientMsgID() {
    
    clientMsgID_ = getDefaultInstance().getClientMsgID();
  }
  /**
   * <code>string clientMsgID = 2;</code>
   * @param value The bytes for clientMsgID to set.
   */
  private void setClientMsgIDBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    clientMsgID_ = value.toStringUtf8();
    
  }

  public static final int SENDTIME_FIELD_NUMBER = 3;
  private long sendTime_;
  /**
   * <code>int64 sendTime = 3;</code>
   * @return The sendTime.
   */
  @java.lang.Override
  public long getSendTime() {
    return sendTime_;
  }
  /**
   * <code>int64 sendTime = 3;</code>
   * @param value The sendTime to set.
   */
  private void setSendTime(long value) {
    
    sendTime_ = value;
  }
  /**
   * <code>int64 sendTime = 3;</code>
   */
  private void clearSendTime() {
    
    sendTime_ = 0L;
  }

  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.openim.android.sdk.protos.sdkws.UserSendMsgResp prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code openim.sdkws.UserSendMsgResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.openim.android.sdk.protos.sdkws.UserSendMsgResp, Builder> implements
      // @@protoc_insertion_point(builder_implements:openim.sdkws.UserSendMsgResp)
      io.openim.android.sdk.protos.sdkws.UserSendMsgRespOrBuilder {
    // Construct using io.openim.android.sdk.protos.sdkws.UserSendMsgResp.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string serverMsgID = 1;</code>
     * @return The serverMsgID.
     */
    @java.lang.Override
    public java.lang.String getServerMsgID() {
      return instance.getServerMsgID();
    }
    /**
     * <code>string serverMsgID = 1;</code>
     * @return The bytes for serverMsgID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerMsgIDBytes() {
      return instance.getServerMsgIDBytes();
    }
    /**
     * <code>string serverMsgID = 1;</code>
     * @param value The serverMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setServerMsgID(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerMsgID(value);
      return this;
    }
    /**
     * <code>string serverMsgID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerMsgID() {
      copyOnWrite();
      instance.clearServerMsgID();
      return this;
    }
    /**
     * <code>string serverMsgID = 1;</code>
     * @param value The bytes for serverMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setServerMsgIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerMsgIDBytes(value);
      return this;
    }

    /**
     * <code>string clientMsgID = 2;</code>
     * @return The clientMsgID.
     */
    @java.lang.Override
    public java.lang.String getClientMsgID() {
      return instance.getClientMsgID();
    }
    /**
     * <code>string clientMsgID = 2;</code>
     * @return The bytes for clientMsgID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClientMsgIDBytes() {
      return instance.getClientMsgIDBytes();
    }
    /**
     * <code>string clientMsgID = 2;</code>
     * @param value The clientMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setClientMsgID(
        java.lang.String value) {
      copyOnWrite();
      instance.setClientMsgID(value);
      return this;
    }
    /**
     * <code>string clientMsgID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientMsgID() {
      copyOnWrite();
      instance.clearClientMsgID();
      return this;
    }
    /**
     * <code>string clientMsgID = 2;</code>
     * @param value The bytes for clientMsgID to set.
     * @return This builder for chaining.
     */
    public Builder setClientMsgIDBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setClientMsgIDBytes(value);
      return this;
    }

    /**
     * <code>int64 sendTime = 3;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return instance.getSendTime();
    }
    /**
     * <code>int64 sendTime = 3;</code>
     * @param value The sendTime to set.
     * @return This builder for chaining.
     */
    public Builder setSendTime(long value) {
      copyOnWrite();
      instance.setSendTime(value);
      return this;
    }
    /**
     * <code>int64 sendTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSendTime() {
      copyOnWrite();
      instance.clearSendTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:openim.sdkws.UserSendMsgResp)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.openim.android.sdk.protos.sdkws.UserSendMsgResp();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "serverMsgID_",
            "clientMsgID_",
            "sendTime_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.openim.android.sdk.protos.sdkws.UserSendMsgResp> parser = PARSER;
        if (parser == null) {
          synchronized (io.openim.android.sdk.protos.sdkws.UserSendMsgResp.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.openim.android.sdk.protos.sdkws.UserSendMsgResp>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:openim.sdkws.UserSendMsgResp)
  private static final io.openim.android.sdk.protos.sdkws.UserSendMsgResp DEFAULT_INSTANCE;
  static {
    UserSendMsgResp defaultInstance = new UserSendMsgResp();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserSendMsgResp.class, defaultInstance);
  }

  public static io.openim.android.sdk.protos.sdkws.UserSendMsgResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserSendMsgResp> PARSER;

  public static com.google.protobuf.Parser<UserSendMsgResp> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

