// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/push.proto

package io.openim.android.sdk.protos.push;

public interface DelUserPushTokenRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:openim.push.DelUserPushTokenResp)
    com.google.protobuf.MessageLiteOrBuilder {
}
