// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/push.proto

package io.openim.android.sdk.protos.push;

public final class Push {
  private Push() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
